// apps/showcase/credit-risk/vue/components/Sparkline.vue
<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{
  data: (number | null)[];
  /** Tooltip x labels — quarters or month-end dates, already formatted. */
  labels?: string[];
  valueFormatter?: (value: number | null) => string;
}>();

const objectProps = computed(() => ({
  data: props.data,
  labels: props.labels,
  valueFormatter: props.valueFormatter,
}));
</script>

<template>
  <md-sparkline v-awc="{ props: objectProps }"></md-sparkline>
</template>

// apps/showcase/credit-risk/angular/src/app/components/sparkline.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';

@Component({
  selector: 'awc-sparkline',
  standalone: true,
  styles: ':host { display: contents; }',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <md-sparkline
      [data]="data"
      [labels]="labels"
      [valueFormatter]="valueFormatter"
      variant="area"
      [attr.color]="color"
      curve="monotone"
      show-marks="extremes"
      height="34px"
    ></md-sparkline>
  `,
})
export class SparklineComponent {
  @Input({ required: true }) data!: (number | null)[];
  /** Tooltip x labels — quarters or month-end dates, already formatted. */
  @Input() labels?: string[];
  @Input() valueFormatter?: (value: number | null) => string;
  @Input() color = 'primary';
}
