// apps/showcase/community/react/src/components/screens/ProfileScreen.tsx
/**
 * Your own profile.
 *
 * NO FRIENDSHIP BUTTON — `friendAction.self` is `null`, and a screen that had
 * to render "add yourself as a friend" has gone wrong somewhere upstream. The
 * timeline, the about panel and the photo grid are all shared with the person
 * drill; the only thing this screen adds is that it is yours.
 */

import { getViewer, profileSummary } from '@awc-ui/showcase-kit/community';
import { useT } from '@/lib/showcase';
import { EmptyState, Panel, Screen } from '@/components/Shell';
import { ProfileSkeleton } from '@/components/skeletons';
import { Count } from '@/components/bits';
import { AboutPanel, PhotoPanel, ProfileHeader } from './ProfileParts';
import { Timeline } from './Timeline';
import { Snackbar, useSnackbar } from './Snackbar';

export function ProfileScreen() {
  const t = useT();
  const { message, say, close } = useSnackbar();
  const summary = profileSummary(getViewer().id);

  return (
    <Screen
      title={t('community.screen.profile.title')}
      subtitle={t('community.screen.profile.subtitle')}
      aside={<Count value={summary.posts.length} />}
      skeleton={<ProfileSkeleton />}
    >
      <div className="columns">
        <div className="columns__main">
          <ProfileHeader summary={summary} />
          <Timeline posts={summary.posts} onMessage={say} />
        </div>
        <aside className="columns__rail">
          <AboutPanel summary={summary} />
          <PhotoPanel summary={summary} />
        </aside>
      </div>

      {summary.posts.length === 0 ? <EmptyState message={t('community.empty.posts')} /> : null}
      <Snackbar message={message} onClose={close} />
    </Screen>
  );
}

// apps/showcase/community/vue/src/components/screens/ProfileScreen.vue
<!-- Your own profile. NO FRIENDSHIP BUTTON — `friendAction.self` is null, and a
     screen that had to render "add yourself as a friend" has gone wrong
     somewhere upstream. -->
<script setup lang="ts">
import { getViewer, profileSummary } from '@awc-ui/showcase-kit/community';
import Screen from '~/components/Screen.vue';
import EmptyState from '~/components/EmptyState.vue';
import ProfileSkeleton from '~/components/skeletons/ProfileSkeleton.vue';
import Count from '~/components/bits/Count.vue';
import ProfileHeader from './ProfileHeader.vue';
import AboutPanel from './AboutPanel.vue';
import PhotoPanel from './PhotoPanel.vue';
import Timeline from './Timeline.vue';
import SnackbarHost from './SnackbarHost.vue';
import { useSnackbar } from './useSnackbar';
import { useT } from '~/composables/useShowcase';

const t = useT();
const { message, say, close } = useSnackbar();
const summary = profileSummary(getViewer().id);
</script>

<template>
  <Screen
    :title="t('community.screen.profile.title')"
    :subtitle="t('community.screen.profile.subtitle')"
  >
    <template #skeleton><ProfileSkeleton /></template>
    <template #aside><Count :value="summary.posts.length" /></template>

    <div class="columns">
      <div class="columns__main">
        <ProfileHeader :summary="summary" />
        <Timeline :posts="summary.posts" @message="say" />
      </div>
      <aside class="columns__rail">
        <AboutPanel :summary="summary" />
        <PhotoPanel :summary="summary" />
      </aside>
    </div>

    <EmptyState v-if="summary.posts.length === 0" :message="t('community.empty.posts')" />
    <SnackbarHost :message="message" @close="close" />
  </Screen>
</template>
