// apps/showcase/community/react/src/components/screens/GroupScreen.tsx
/**
 * One group: its cover, what it is for, its feed, its events and who posts in
 * it.
 *
 * A PRIVATE GROUP THE VIEWER IS NOT IN SHOWS ITS ABOUT AND NOTHING ELSE, which
 * is the whole reason `GroupPrivacy` exists as data rather than as a chip. The
 * posts are withheld and the screen SAYS they are withheld — an empty feed with
 * no explanation reads as a dead group, and a private group that showed its
 * posts anyway would make the flag a decoration.
 */

import { getGroupBySlug, groupSummary, joinAction } from '@awc-ui/showcase-kit/community';
import { Link } from '@/lib/router';
import { route } from '@/lib/routes';
import { useT } from '@/lib/showcase';
import { useEngagement } from '@/lib/engagement';
import { EmptyState, Panel, Screen } from '@/components/Shell';
import { CoverSkeleton } from '@/components/skeletons';
import { Avatar, Count, DateText, Media, PrivacyChip, RoleChip } from '@/components/bits';
import { Timeline } from './Timeline';
import { EventRailRow } from './EventsScreen';
import { NotFoundScreen } from './NotFoundScreen';
import { Snackbar, useSnackbar } from './Snackbar';

export function GroupScreen({ slug }: { slug: string }) {
  const t = useT();
  const { roleFor, setRole } = useEngagement();
  const { message, say, close } = useSnackbar();

  const found = getGroupBySlug(slug);
  if (!found) return <NotFoundScreen />;

  const summary = groupSummary(found.id);
  const { group, posts, events, contributors } = summary;
  const role = roleFor(group);
  const action = joinAction[role];
  const member = role === 'admin' || role === 'moderator' || role === 'member';
  const hidden = group.privacy === 'private' && !member;

  return (
    <Screen
      title={group.name}
      subtitle={t('community.screen.group.subtitle')}
      crumbLabel={group.name}
      aside={<Count value={group.memberCount} compact />}
      skeleton={<CoverSkeleton timeline />}
    >
      <div className="columns">
        <div className="columns__main">
          <Panel>
            <Media media={group.cover} className="event-cover" eager />
            <h2 className="profile-head__name">{group.name}</h2>
            <div className="row">
              <PrivacyChip group={group} />
              <RoleChip group={{ ...group, role, roleKey: `community.role.${role}` }} />
              <span className="person-row__meta">
                <Count value={group.memberCount} compact />{' '}
                {t('community.count.members').toLocaleLowerCase(t.locale)}
              </span>
              {action ? (
                <md-button
                  variant={action.variant}
                  icon={action.icon}
                  onClick={() => {
                    const next =
                      role === 'none' ? (group.privacy === 'private' ? 'pending' : 'member') : 'none';
                    setRole(group, next);
                    say(
                      next === 'member'
                        ? 'community.msg.joined'
                        : next === 'pending'
                          ? 'community.msg.requested'
                          : role === 'pending'
                            ? 'community.msg.requestCancelled'
                            : 'community.msg.left',
                      { name: group.name },
                    );
                  }}
                >
                  {t(action.labelKey)}
                </md-button>
              ) : null}
            </div>
            <p>{t(group.descriptionKey)}</p>
            {group.joinedAt ? (
              <p className="person-row__meta">
                {t('community.hint.joinedGroup', { date: '' })}
                <DateText at={group.joinedAt} style="long" />
              </p>
            ) : null}
          </Panel>

          {hidden ? (
            <EmptyState message={t('community.hint.privateGroup')} />
          ) : posts.length === 0 ? (
            <EmptyState message={t('community.empty.posts')} />
          ) : (
            <Timeline posts={posts} onMessage={say} />
          )}
        </div>

        <aside className="columns__rail">
          {events.length > 0 ? (
            <Panel title={t('community.panel.groupEvents')} actions={<Count value={events.length} />}>
              {/* The RAIL variant — a 300px column cannot hold the list row's
                  three tracks, and a rail states what is coming up rather than
                  offering to answer it. See EventsScreen. */}
              <div className="rail-block">
                {events.map((event) => (
                  <EventRailRow key={event.id} event={event} />
                ))}
              </div>
            </Panel>
          ) : null}

          <Panel title={t('community.panel.members')} actions={<Count value={contributors.length} />}>
            {contributors.length === 0 ? (
              <EmptyState message={t('community.empty.members')} />
            ) : (
              <div className="rail-block">
                {contributors.map((person) => (
                  <Link key={person.id} className="rail-row" href={route.person(person.handle)}>
                    <Avatar person={person} size="small" />
                    <span className="rail-row__text">
                      <span className="rail-row__name">{person.displayName}</span>
                    </span>
                  </Link>
                ))}
              </div>
            )}
          </Panel>
        </aside>
      </div>

      <Snackbar message={message} onClose={close} />
    </Screen>
  );
}

// apps/showcase/community/svelte/src/lib/screens/GroupScreen.svelte
<!-- A PRIVATE GROUP THE VIEWER IS NOT IN SHOWS ITS ABOUT AND NOTHING ELSE, and
     SAYS the posts are withheld — an empty feed with no explanation reads as a
     dead group, and one that showed its posts anyway would make the flag a
     decoration. -->
<script lang="ts">
  import { getGroupBySlug, groupSummary, joinAction } from '@awc-ui/showcase-kit/community';
  import Screen from '$lib/components/Screen.svelte';
  import Panel from '$lib/components/Panel.svelte';
  import Drill from '$lib/components/Drill.svelte';
  import EmptyState from '$lib/components/EmptyState.svelte';
  import CoverSkeleton from '$lib/skeletons/CoverSkeleton.svelte';
  import Avatar from '$lib/bits/Avatar.svelte';
  import Count from '$lib/bits/Count.svelte';
  import DateText from '$lib/bits/DateText.svelte';
  import Media from '$lib/bits/Media.svelte';
  import PrivacyChip from '$lib/bits/PrivacyChip.svelte';
  import RoleChip from '$lib/bits/RoleChip.svelte';
  import EventRailRow from './EventRailRow.svelte';
  import Timeline from './Timeline.svelte';
  import NotFoundScreen from './NotFoundScreen.svelte';
  import SnackbarHost from './SnackbarHost.svelte';
  import { createSnackbar } from './snackbar';
  import { roleFor, roles, setRole } from '$lib/engagement';
  import { route } from '$lib/routes';
  import { t } from '$lib/showcase';

  export let slug: string;
  const { message, say, close } = createSnackbar();

  $: found = getGroupBySlug(slug);
  $: summary = found ? groupSummary(found.id) : null;
  $: role = found ? roleFor($roles, found) : 'none';
  $: action = joinAction[role];
  $: member = ['admin', 'moderator', 'member'].includes(role);
  $: hidden = summary?.group.privacy === 'private' && !member;

  function press() {
    if (!found) return;
    const was = role;
    const next = was === 'none' ? (found.privacy === 'private' ? 'pending' : 'member') : 'none';
    setRole(found, next);
    say(
      next === 'member'
        ? 'community.msg.joined'
        : next === 'pending'
          ? 'community.msg.requested'
          : was === 'pending'
            ? 'community.msg.requestCancelled'
            : 'community.msg.left',
      { name: found.name },
    );
  }
</script>

{#if !summary}
  <NotFoundScreen />
{:else}
  <Screen
    title={summary.group.name}
    subtitle={$t('community.screen.group.subtitle')}
    crumbLabel={summary.group.name}
  >
    <svelte:fragment slot="skeleton"><CoverSkeleton timeline /></svelte:fragment>
    <svelte:fragment slot="aside"><Count value={summary.group.memberCount} compact /></svelte:fragment>

    <div class="columns">
      <div class="columns__main">
        <Panel>
          <Media media={summary.group.cover} className="event-cover" eager />
          <h2 class="profile-head__name">{summary.group.name}</h2>
          <div class="row">
            <PrivacyChip group={summary.group} />
            <RoleChip {role} />
            <span class="person-row__meta">
              <Count value={summary.group.memberCount} compact />
              {$t('community.count.members').toLocaleLowerCase($t.locale)}
            </span>
            {#if action}
              <md-button variant={action.variant} icon={action.icon} on:mdClick={press}>
                {$t(action.labelKey)}
              </md-button>
            {/if}
          </div>
          <p>{$t(summary.group.descriptionKey)}</p>
          {#if summary.group.joinedAt}
            <p class="person-row__meta">
              {$t('community.hint.joinedGroup', { date: '' })}<DateText
                at={summary.group.joinedAt}
                format="long"
              />
            </p>
          {/if}
        </Panel>

        {#if hidden}
          <EmptyState message={$t('community.hint.privateGroup')} />
        {:else if summary.posts.length === 0}
          <EmptyState message={$t('community.empty.posts')} />
        {:else}
          <Timeline posts={summary.posts} on:message={(e) => say(e.detail.key, e.detail.params)} />
        {/if}
      </div>

      <aside class="columns__rail">
        {#if summary.events.length > 0}
          <Panel title={$t('community.panel.groupEvents')}>
            <svelte:fragment slot="actions"><Count value={summary.events.length} /></svelte:fragment>
            <!-- The RAIL variant: a 300px column cannot hold the list row's
                 three tracks. -->
            <div class="rail-block">
              {#each summary.events as event (event.id)}
                <EventRailRow {event} />
              {/each}
            </div>
          </Panel>
        {/if}

        <Panel title={$t('community.panel.members')}>
          <svelte:fragment slot="actions"><Count value={summary.contributors.length} /></svelte:fragment>
          {#if summary.contributors.length === 0}
            <EmptyState message={$t('community.empty.members')} />
          {:else}
            <div class="rail-block">
              {#each summary.contributors as person (person.id)}
                <Drill linkClass="rail-row" href={route.person(person.handle)}>
                  <Avatar {person} size="small" />
                  <span class="rail-row__text">
                    <span class="rail-row__name">{person.displayName}</span>
                  </span>
                </Drill>
              {/each}
            </div>
          {/if}
        </Panel>
      </aside>
    </div>

    <SnackbarHost message={$message} on:close={close} />
  </Screen>
{/if}
