// apps/showcase/community/vue/src/components/screens/PersonScreen.vue
<!--
  Somebody else's profile.

  THE VIEWER'S OWN HANDLE RENDERS THEIR OWN SCREEN rather than a read-only copy
  of it: both URLs resolve, and answering with a page that offered to befriend
  yourself is the state `friendAction.self` exists to prevent.
-->
<script setup lang="ts">
import { computed } from 'vue';
import { getPersonByHandle, getViewer, profileSummary } from '@awc-ui/showcase-kit/community';
import Screen from '~/components/Screen.vue';
import EmptyState from '~/components/EmptyState.vue';
import ProfileSkeleton from '~/components/skeletons/ProfileSkeleton.vue';
import Count from '~/components/bits/Count.vue';
import FriendButton from '~/components/bits/FriendButton.vue';
import ProfileHeader from './ProfileHeader.vue';
import AboutPanel from './AboutPanel.vue';
import PhotoPanel from './PhotoPanel.vue';
import Timeline from './Timeline.vue';
import NotFoundScreen from './NotFoundScreen.vue';
import ProfileScreen from './ProfileScreen.vue';
import SnackbarHost from './SnackbarHost.vue';
import { useSnackbar } from './useSnackbar';
import { useEngagement } from '~/composables/useEngagement';
import { useT } from '~/composables/useShowcase';

const props = defineProps<{ handle: string }>();
const t = useT();
const { friendshipFor, setFriendship } = useEngagement();
const { message, say, close } = useSnackbar();

const person = computed(() => getPersonByHandle(props.handle));
const isSelf = computed(() => person.value?.id === getViewer().id);
const summary = computed(() => (person.value ? profileSummary(person.value.id) : null));
</script>

<template>
  <NotFoundScreen v-if="!person" />
  <ProfileScreen v-else-if="isSelf" />
  <Screen
    v-else-if="summary"
    :title="person.displayName"
    :subtitle="t('community.screen.person.subtitle')"
    :crumb-label="person.displayName"
  >
    <template #skeleton><ProfileSkeleton /></template>
    <template #aside><Count :value="summary.posts.length" /></template>

    <div class="columns">
      <div class="columns__main">
        <ProfileHeader :summary="summary">
          <template #action>
            <FriendButton
              :person="person"
              :state="friendshipFor(person)"
              size="md"
              @act="
                (next) => {
                  const was = friendshipFor(person!);
                  setFriendship(person!, next);
                  say(
                    next === 'outgoing'
                      ? 'community.msg.friendRequested'
                      : next === 'friend'
                        ? 'community.msg.friendAccepted'
                        : was === 'friend'
                          ? 'community.msg.friendRemoved'
                          : 'community.msg.requestCancelled',
                    { name: person!.displayName },
                  );
                }
              "
            />
          </template>
        </ProfileHeader>
        <EmptyState v-if="summary.posts.length === 0" :message="t('community.empty.posts')" />
        <Timeline v-else :posts="summary.posts" @message="say" />
      </div>
      <aside class="columns__rail">
        <AboutPanel :summary="summary" />
        <PhotoPanel :summary="summary" />
      </aside>
    </div>

    <SnackbarHost :message="message" @close="close" />
  </Screen>
</template>

// apps/showcase/community/svelte/src/lib/screens/PersonScreen.svelte
<!-- THE VIEWER'S OWN HANDLE RENDERS THEIR OWN SCREEN rather than a read-only
     copy: both URLs resolve, and offering to befriend yourself is the state
     `friendAction.self` exists to prevent. -->
<script lang="ts">
  import { getPersonByHandle, getViewer, profileSummary } from '@awc-ui/showcase-kit/community';
  import Screen from '$lib/components/Screen.svelte';
  import EmptyState from '$lib/components/EmptyState.svelte';
  import ProfileSkeleton from '$lib/skeletons/ProfileSkeleton.svelte';
  import Count from '$lib/bits/Count.svelte';
  import FriendButton from '$lib/bits/FriendButton.svelte';
  import ProfileHeader from './ProfileHeader.svelte';
  import AboutPanel from './AboutPanel.svelte';
  import PhotoPanel from './PhotoPanel.svelte';
  import Timeline from './Timeline.svelte';
  import NotFoundScreen from './NotFoundScreen.svelte';
  import ProfileScreen from './ProfileScreen.svelte';
  import SnackbarHost from './SnackbarHost.svelte';
  import { createSnackbar } from './snackbar';
  import { friendshipFor, friendships, setFriendship } from '$lib/engagement';
  import { t } from '$lib/showcase';

  export let handle: string;
  const { message, say, close } = createSnackbar();

  $: person = getPersonByHandle(handle);
  $: isSelf = person?.id === getViewer().id;
  $: summary = person ? profileSummary(person.id) : null;
</script>

{#if !person}
  <NotFoundScreen />
{:else if isSelf}
  <ProfileScreen />
{:else if summary}
  <Screen
    title={person.displayName}
    subtitle={$t('community.screen.person.subtitle')}
    crumbLabel={person.displayName}
  >
    <svelte:fragment slot="skeleton"><ProfileSkeleton /></svelte:fragment>
    <svelte:fragment slot="aside"><Count value={summary.posts.length} /></svelte:fragment>

    <div class="columns">
      <div class="columns__main">
        <ProfileHeader {summary}>
          <svelte:fragment slot="action">
            <FriendButton
              {person}
              state={friendshipFor($friendships, person)}
              size="md"
              on:act={(e) => {
                const was = friendshipFor($friendships, person);
                setFriendship(person, e.detail);
                say(
                  e.detail === 'outgoing'
                    ? 'community.msg.friendRequested'
                    : e.detail === 'friend'
                      ? 'community.msg.friendAccepted'
                      : was === 'friend'
                        ? 'community.msg.friendRemoved'
                        : 'community.msg.requestCancelled',
                  { name: person.displayName },
                );
              }}
            />
          </svelte:fragment>
        </ProfileHeader>
        {#if summary.posts.length === 0}
          <EmptyState message={$t('community.empty.posts')} />
        {:else}
          <Timeline posts={summary.posts} on:message={(e) => say(e.detail.key, e.detail.params)} />
        {/if}
      </div>
      <aside class="columns__rail">
        <AboutPanel {summary} />
        <PhotoPanel {summary} />
      </aside>
    </div>

    <SnackbarHost message={$message} on:close={close} />
  </Screen>
{/if}
