// apps/showcase/community/vue/src/components/screens/ProfileScreen.vue
<!-- Your own profile. NO FRIENDSHIP BUTTON — `friendAction.self` is null, and a
     screen that had to render "add yourself as a friend" has gone wrong
     somewhere upstream. -->
<script setup lang="ts">
import { getViewer, profileSummary } from '@awc-ui/showcase-kit/community';
import Screen from '~/components/Screen.vue';
import EmptyState from '~/components/EmptyState.vue';
import ProfileSkeleton from '~/components/skeletons/ProfileSkeleton.vue';
import Count from '~/components/bits/Count.vue';
import ProfileHeader from './ProfileHeader.vue';
import AboutPanel from './AboutPanel.vue';
import PhotoPanel from './PhotoPanel.vue';
import Timeline from './Timeline.vue';
import SnackbarHost from './SnackbarHost.vue';
import { useSnackbar } from './useSnackbar';
import { useT } from '~/composables/useShowcase';

const t = useT();
const { message, say, close } = useSnackbar();
const summary = profileSummary(getViewer().id);
</script>

<template>
  <Screen
    :title="t('community.screen.profile.title')"
    :subtitle="t('community.screen.profile.subtitle')"
  >
    <template #skeleton><ProfileSkeleton /></template>
    <template #aside><Count :value="summary.posts.length" /></template>

    <div class="columns">
      <div class="columns__main">
        <ProfileHeader :summary="summary" />
        <Timeline :posts="summary.posts" @message="say" />
      </div>
      <aside class="columns__rail">
        <AboutPanel :summary="summary" />
        <PhotoPanel :summary="summary" />
      </aside>
    </div>

    <EmptyState v-if="summary.posts.length === 0" :message="t('community.empty.posts')" />
    <SnackbarHost :message="message" @close="close" />
  </Screen>
</template>

// apps/showcase/community/svelte/src/lib/screens/ProfileScreen.svelte
<!-- NO FRIENDSHIP BUTTON — `friendAction.self` is null, and a screen that had
     to render "add yourself as a friend" has gone wrong upstream. -->
<script lang="ts">
  import { getViewer, profileSummary } from '@awc-ui/showcase-kit/community';
  import Screen from '$lib/components/Screen.svelte';
  import EmptyState from '$lib/components/EmptyState.svelte';
  import ProfileSkeleton from '$lib/skeletons/ProfileSkeleton.svelte';
  import Count from '$lib/bits/Count.svelte';
  import ProfileHeader from './ProfileHeader.svelte';
  import AboutPanel from './AboutPanel.svelte';
  import PhotoPanel from './PhotoPanel.svelte';
  import Timeline from './Timeline.svelte';
  import SnackbarHost from './SnackbarHost.svelte';
  import { createSnackbar } from './snackbar';
  import { t } from '$lib/showcase';

  const summary = profileSummary(getViewer().id);
  const { message, say, close } = createSnackbar();
</script>

<Screen
  title={$t('community.screen.profile.title')}
  subtitle={$t('community.screen.profile.subtitle')}
>
  <svelte:fragment slot="skeleton"><ProfileSkeleton /></svelte:fragment>
  <svelte:fragment slot="aside"><Count value={summary.posts.length} /></svelte:fragment>

  <div class="columns">
    <div class="columns__main">
      <ProfileHeader {summary} />
      <Timeline posts={summary.posts} on:message={(e) => say(e.detail.key, e.detail.params)} />
    </div>
    <aside class="columns__rail">
      <AboutPanel {summary} />
      <PhotoPanel {summary} />
    </aside>
  </div>

  {#if summary.posts.length === 0}
    <EmptyState message={$t('community.empty.posts')} />
  {/if}
  <SnackbarHost message={$message} on:close={close} />
</Screen>
