// apps/showcase/community/vue/src/components/bits/Count.vue
<!--
  A count.

  COMPACT ABOVE TEN THOUSAND, EXACT BELOW IT. Higher than Lyra's threshold and
  deliberately: the numbers here are members, friends and reactions, all of
  which a reader compares between rows — "1.2K members" against "1.4K members"
  is a comparison the rounding has already thrown away.
-->
<script setup lang="ts">
import { useT } from '~/composables/useShowcase';

const props = withDefaults(defineProps<{ value: number; compact?: boolean }>(), { compact: false });
const t = useT();
</script>

<template>
  <span class="num">{{
    t.formatNumber(
      props.value,
      props.compact && props.value >= 10_000
        ? { notation: 'compact', maximumFractionDigits: 1 }
        : { maximumFractionDigits: 0 },
    )
  }}</span>
</template>

// apps/showcase/community/svelte/src/lib/bits/Count.svelte
<!--
  A count. COMPACT ABOVE TEN THOUSAND, EXACT BELOW IT — the numbers here are
  members, friends and reactions, all of which a reader compares between rows,
  and "1.2K" against "1.4K" is a comparison the rounding has thrown away.
-->
<script lang="ts">
  import { t } from '$lib/showcase';
  export let value: number;
  export let compact = false;
</script>

<span class="num"
  >{$t.formatNumber(
    value,
    compact && value >= 10_000
      ? { notation: 'compact', maximumFractionDigits: 1 }
      : { maximumFractionDigits: 0 },
  )}</span
>
