// apps/showcase/community/vue/src/components/bits/RsvpChip.vue
<!-- An RSVP state. `none` and `declined` earn no chip. -->
<script setup lang="ts">
import { rsvpIcon, rsvpTone, type Rsvp } from '@awc-ui/showcase-kit/community';
import StateChip from './StateChip.vue';

const props = defineProps<{ rsvp: Rsvp }>();
</script>

<template>
  <StateChip
    v-if="rsvpTone[props.rsvp]"
    :label-key="`community.rsvp.${props.rsvp}`"
    :color="rsvpTone[props.rsvp] ?? undefined"
    :icon="rsvpIcon[props.rsvp]"
  />
</template>

// apps/showcase/community/svelte/src/lib/bits/RsvpChip.svelte
<script lang="ts">
  import { rsvpIcon, rsvpTone, type Rsvp } from '@awc-ui/showcase-kit/community';
  import StateChip from './StateChip.svelte';
  export let rsvp: Rsvp;
</script>

{#if rsvpTone[rsvp]}
  <StateChip
    labelKey={`community.rsvp.${rsvp}`}
    color={rsvpTone[rsvp] ?? undefined}
    icon={rsvpIcon[rsvp]}
  />
{/if}
