// apps/showcase/music/react/src/components/bits.tsx
/**
 * The small pieces every screen composes from.
 *
 * ANYTHING RENDERED THE SAME WAY ON TWO SCREENS BELONGS HERE. A track row is on
 * five screens and a peak strip on four; written twice they would be identical
 * until the first correction, and the correction is always applied to one of
 * them. Everything here is presentational — it takes what it draws and reaches
 * for the player only where the thing it draws IS a control.
 */

import {
  MAX_BARS,
  REPORTING_INSTANT,
  albumById,
  artistById,
  clock,
  libraryIcon,
  panPosition,
  trackIcon,
  trackLabelKey,
  volumeDb,
  type Album,
  type Artist,
  type Artwork,
  type Playlist,
  type StudioTrack,
  type Track,
} from '@awc-ui/showcase-kit/music';
import type { ReactNode } from 'react';
import { useT } from '@/lib/showcase';
import { Link } from '@/lib/router';
import { route, withBase } from '@/lib/routes';
import { usePlayer } from '@/lib/player';

/* ------------------------------------------------------------------ numbers */

/**
 * A number, formatted for the reader's locale.
 *
 * `compact` only above ten thousand. Below that the compact form loses more
 * than it saves — "9.9k plays" hides whether that is 9,900 or 9,949, and a play
 * count is a number a reader compares.
 */
export function Count({ value, compact = false }: { value: number; compact?: boolean }) {
  const t = useT();
  return (
    <span className="num">
      {t.formatNumber(
        value,
        compact && value >= 10_000
          ? { notation: 'compact', maximumFractionDigits: 1 }
          : { maximumFractionDigits: 0 },
      )}
    </span>
  );
}

/**
 * A duration or a position, as mm:ss.
 *
 * `clock()` from the kit, and NOT `Intl` — see the note on it. The digits stay
 * Latin in every locale so the scrubber's two readouts and the ruler's bar
 * numbers do not end up in two different numbering systems on the same screen.
 */
export function Clock({ seconds }: { seconds: number }) {
  return <span className="tabular">{clock(seconds)}</span>;
}

/** How long ago, in words, inside a `<time>` that still carries the instant. */
export function When({ at }: { at: string }) {
  const t = useT();
  return (
    <time dateTime={at} title={t.formatDate(at.slice(0, 10), 'long')} className="when">
      {t.formatRelativeTime(at, REPORTING_INSTANT, { style: 'narrow' })}
    </time>
  );
}

/** A calendar date, for a project's "updated" line. */
export function DateText({ at }: { at: string }) {
  const t = useT();
  return <time dateTime={at}>{t.formatDate(at.slice(0, 10), 'medium')}</time>;
}

/* ------------------------------------------------------------------ artwork */

/**
 * Cover art.
 *
 * `altKey` IS MANDATORY on every `Artwork` in the fixture and this is the only
 * place an `<img>` is written, so there is exactly one function that could
 * forget to resolve it. Generated abstract artwork is not self-explanatory the
 * way a photograph is, which is why the rule exists at all.
 */
export function Art({
  art,
  className,
  eager = false,
}: {
  art: Artwork;
  className?: string;
  eager?: boolean;
}) {
  const t = useT();
  return (
    <img
      className={className}
      src={art.src}
      alt={t(art.altKey)}
      loading={eager ? 'eager' : 'lazy'}
      decoding="async"
      draggable={false}
    />
  );
}

/* -------------------------------------------------------------- peak strips */

/**
 * A run of loudness samples as bars.
 *
 * THE HEIGHT IS A DATA ATTRIBUTE, NOT A STYLE. `style-src-attr 'none'` refuses
 * `style="height: 62%"`, so each sample is rounded to one of eleven buckets and
 * `app.css` carries a rule per bucket. Coarser than the data and imperceptible
 * at three pixels wide.
 *
 * `aria-hidden`, because it is a texture rather than information: the numbers a
 * reader needs are the duration and the title beside it, and sixteen unlabelled
 * bars announced individually would be noise.
 */
export function Peaks({ peaks }: { peaks: readonly number[] }) {
  return (
    <span className="peaks" aria-hidden="true">
      {peaks.map((value, index) => (
        <span key={index} className="peaks__bar" data-h={Math.round(Math.max(0, Math.min(1, value)) * 10)} />
      ))}
    </span>
  );
}

/* ------------------------------------------------------------- track naming */

/** An artist's name as a link, or plain text when the artist is missing. */
export function ArtistLink({ id }: { id: string }) {
  const artist = artistById(id);
  if (!artist) return null;
  return (
    <Link className="link" href={withBase(route.artist(artist.handle))}>
      {artist.name}
    </Link>
  );
}

/** An album's title as a link. */
export function AlbumLink({ id }: { id: string }) {
  const album = albumById(id);
  if (!album) return null;
  return (
    <Link className="link" href={withBase(route.album(album.slug))}>
      {album.title}
    </Link>
  );
}

/* ------------------------------------------------------------- track rows */

/**
 * One row in a track list.
 *
 * IT MARKS ITSELF WHEN IT IS THE LOADED TRACK, on every screen that lists it —
 * `data-current` comes from the transport, so a reader never has to look at the
 * bar to find where they are. That is the visible payoff of holding the
 * transport above the router.
 *
 * THE WHOLE ROW IS NOT A LINK. It carries a play button, a like button and a
 * link to the track, and a control inside an anchor fires both on a keyboard
 * press. The title is the link; the row is a grid.
 */
export function TrackRow({
  track,
  index,
  showArtist = true,
  showAlbum = false,
}: {
  track: Track;
  index?: number;
  showArtist?: boolean;
  /**
   * A middle column naming the album.
   *
   * ON BY DEFAULT ONLY WHERE IT SAYS SOMETHING. A list drawn from across the
   * library — Home, Liked, the queue — has a different album on every row, and
   * without it the row is a short label on the left and a duration on the far
   * right with a hand's width of nothing between them. On an ALBUM screen every
   * row would repeat the title above it, which is noise. The list decides,
   * because every row in one list has to agree or the columns stop lining up.
   */
  showAlbum?: boolean;
}) {
  const t = useT();
  const player = usePlayer();
  const current = player.transport.trackId === track.id;
  const liked = player.likedFor(track);

  return (
    <div className="track-row" data-track={track.id} data-current={current ? '' : undefined}>
      <span className="track-row__index">{index ?? track.trackNumber}</span>
      <span className="track-row__text">
        <Link className="track-row__title link" href={withBase(route.track(track.id))}>
          {track.title}
        </Link>
        {showArtist ? (
          <span className="track-row__meta">
            <ArtistLink id={track.artistId} />
          </span>
        ) : null}
      </span>
      {showAlbum ? (
        <span className="track-row__album">
          <AlbumLink id={track.albumId} />
        </span>
      ) : null}
      <span className="track-row__time">
        <Clock seconds={track.durationSec} />
      </span>
      <span className="row">
        {/*
          * `toggle` + `selected` + `selectedIcon`, WHICH IS WHAT THE COMPONENT
          * IS FOR — and this was `color="primary"` first, an attribute
          * `md-icon-button` does not have. An unknown attribute is not an
          * error: it sat in the markup doing nothing, so a liked track swapped
          * its glyph and stayed exactly the same grey as an unliked one. The
          * component's own toggle mode paints the selected state, which is the
          * difference between "this control exists" and "this control is on".
          *
          * THE GLYPH IS STILL DRIVEN FROM `icon` rather than `selected-icon`.
          * Both were set at first and only the tint changed — the heart stayed
          * an outline while turning primary, which reads as a hover rather than
          * a state. Setting `icon` from the liked flag is one source of truth
          * for the shape and cannot half-apply.
          *
          * The name says WHICH track, because a list of twelve buttons all
          * called "Like" tells a screen-reader user nothing about which one
          * they are on.
          */}
        <md-icon-button
          class="track-row__like"
          toggle
          selected={liked || undefined}
          icon={liked ? 'favorite' : 'favorite_border'}
          size="sm"
          data-liked={liked ? '' : undefined}
          aria-label={`${t(liked ? 'music.action.unlike' : 'music.action.like')}: ${track.title}`}
          onClick={() => player.toggleLike(track)}
        />
        <md-icon-button
          class="track-row__play"
          icon={current && player.transport.state === 'playing' ? 'pause' : 'play_arrow'}
          size="sm"
          aria-label={`${t('music.action.play')}: ${track.title}`}
          onClick={() => (current ? player.toggle() : player.play(track))}
        />
      </span>
    </div>
  );
}

/** A whole list of them, numbered by position rather than by track number. */
export function TrackList({
  tracks,
  numbered = false,
  showArtist = true,
  showAlbum = false,
}: {
  tracks: readonly Track[];
  numbered?: boolean;
  showArtist?: boolean;
  showAlbum?: boolean;
}) {
  /* The COLUMN COUNT lives on the list, not the row: rows in one list must all
     use the same grid template or the durations form a ragged edge, which is
     the whole reason a row is a grid rather than a flex line. */
  return (
    <div className="track-list" data-albums={showAlbum ? '' : undefined}>
      {tracks.map((track, at) => (
        <TrackRow
          key={track.id}
          track={track}
          index={numbered ? track.trackNumber : at + 1}
          showArtist={showArtist}
          showAlbum={showAlbum}
        />
      ))}
    </div>
  );
}

/* ---------------------------------------------------------------- shelves */

/** A square card for an album or a project, or a wide one for a playlist. */
export function ShelfCard({
  href,
  art,
  title,
  meta,
}: {
  href: string;
  art: Artwork;
  title: string;
  meta?: ReactNode;
}) {
  return (
    <Link className="shelf-card" href={href}>
      <Art art={art} className={`shelf-card__art${art.shape === 'wide' ? ' shelf-card__art--wide' : ''}`} />
      <span className="shelf-card__title">{title}</span>
      {meta ? <span className="shelf-card__meta">{meta}</span> : null}
    </Link>
  );
}

export function AlbumCard({ album }: { album: Album }) {
  return (
    <ShelfCard
      href={withBase(route.album(album.slug))}
      art={album.art}
      title={album.title}
      meta={<ArtistName id={album.artistId} />}
    />
  );
}

/** The artist's name as TEXT, for inside a card that is already a link. */
export function ArtistName({ id }: { id: string }) {
  return <>{artistById(id)?.name ?? ''}</>;
}

export function PlaylistCard({ playlist }: { playlist: Playlist }) {
  const t = useT();
  return (
    <ShelfCard
      href={withBase(route.library())}
      art={playlist.art}
      title={playlist.title}
      meta={t('music.count.tracks', { count: t.formatNumber(playlist.trackIds.length) })}
    />
  );
}

export function ArtistRow({ artist }: { artist: Artist }) {
  const t = useT();
  return (
    <Link className="artist-row" href={withBase(route.artist(artist.handle))}>
      <Art art={artist.art} className="artist-row__art" />
      <span className="track-row__text">
        <span className="track-row__title">{artist.name}</span>
        <span className="track-row__meta">
          {t('music.label.listeners', { count: t.formatNumber(artist.monthlyListeners, { notation: 'compact', maximumFractionDigits: 1 }) })}
        </span>
      </span>
    </Link>
  );
}

/* ----------------------------------------------------------- studio bits */

/** A studio track's icon and translated kind. */
export function TrackKindMark({ track }: { track: StudioTrack }) {
  const t = useT();
  return (
    <>
      <span className="material-symbols-outlined" aria-hidden="true">
        {trackIcon[track.kind]}
      </span>
      <span className="visually-hidden">{t(trackLabelKey[track.kind])}</span>
    </>
  );
}

/**
 * A fader's decibel readout, or the word for silence.
 *
 * `volumeDb()` returns null at zero rather than `-Infinity`, and this is the
 * only place that decision is visible: a fader pulled all the way down reads
 * "Silent", not "-Infinity dB".
 */
export function VolumeReadout({ volume }: { volume: number }) {
  const t = useT();
  const db = volumeDb(volume);
  return (
    <span className="strip__readout">
      {db === null ? t('music.label.silent') : t('music.label.decibels', { value: t.formatNumber(db, { maximumFractionDigits: 1 }) })}
    </span>
  );
}

/** A pan position, as a side and an amount — never a signed number. */
export function PanReadout({ pan }: { pan: number }) {
  const t = useT();
  const position = panPosition(pan);
  if (position.side === 'centre') return <span className="strip__readout">{t('music.label.panCentre')}</span>;
  return (
    <span className="strip__readout">
      {t(position.side === 'left' ? 'music.label.panLeft' : 'music.label.panRight', {
        amount: t.formatNumber(position.amount),
      })}
    </span>
  );
}

/** The library kind icon, for a row that could be any of three things. */
export function KindIcon({ kind }: { kind: 'album' | 'playlist' | 'artist' }) {
  return (
    <span className="material-symbols-outlined" aria-hidden="true">
      {libraryIcon[kind]}
    </span>
  );
}

export { MAX_BARS };

// apps/showcase/music/angular/src/app/components/bits.component.ts
/**
 * The small, repeated pieces: a count, a clock, cover art, a peak strip, a
 * track row and the shelf cards.
 *
 * EVERY BINDING ONTO AN md-* ELEMENT IS [attr.x], NEVER [x].
 *
 * A lazily-hydrated custom element does not have the property yet when Angular
 * first binds, so a plain [icon] sets a field on a plain HTMLElement and the
 * component never sees it. The attribute form always lands, and Stencil reads
 * attributes on upgrade. This is the single most repeated correction in the
 * Angular ports and it fails silently every time.
 *
 * AND A BOOLEAN-ISH ATTRIBUTE IS ? '' : null, NOT ? true : false. Presence is
 * what these mean, and null is what removes an attribute in Angular — false
 * would render the literal string "false" and read as on.
 */
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  Input,
  inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import {
  albumById,
  artistById,
  clock,
  panPosition,
  volumeDb,
  type Album,
  type Artist,
  type Artwork,
  type Playlist,
  type Track,
} from '@awc-ui/showcase-kit/music';
import { ShowcaseService } from '../lib/showcase.service';
import { PlayerService } from '../lib/player.service';
import { appPath, route } from '../lib/routes';

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-count',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<span class="num">{{ text }}</span>`,
})
export class CountComponent {
  private readonly showcase = inject(ShowcaseService);
  @Input({ required: true }) value!: number;
  /** "compact" only above ten thousand: below that it hides whether "9.9k" is
      9,900 or 9,949, and a play count is a number a reader compares. */
  @Input() compact = false;

  get text(): string {
    return this.showcase.t.formatNumber(
      this.value,
      this.compact && this.value >= 10_000
        ? { notation: 'compact', maximumFractionDigits: 1 }
        : { maximumFractionDigits: 0 },
    );
  }
}

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-clock',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<span class="tabular">{{ text }}</span>`,
})
export class ClockComponent {
  @Input({ required: true }) seconds!: number;
  /* "clock()" from the kit, NOT "Intl": the digits stay Latin in every locale
     so the scrubber and the ruler's bar numbers cannot end up in two different
     numbering systems on one screen. */
  get text(): string { return clock(this.seconds); }
}

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-art',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<img
    [class]="className"
    [src]="art.src"
    [alt]="t(art.altKey)"
    [attr.loading]="eager ? 'eager' : 'lazy'"
    decoding="async"
    draggable="false"
  />`,
})
export class ArtComponent {
  private readonly showcase = inject(ShowcaseService);
  @Input({ required: true }) art!: Artwork;
  @Input() className = '';
  @Input() eager = false;
  /* "altKey" is mandatory on every "Artwork", and this is the only place an
     "<img>" is written — so there is exactly one function that could forget. */
  t = (key: string) => this.showcase.t(key);
}

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-peaks',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<span class="peaks" aria-hidden="true"
    ><span *ngFor="let value of peaks" class="peaks__bar" [attr.data-h]="bucket(value)"></span
  ></span>`,
})
export class PeaksComponent {
  @Input({ required: true }) peaks!: readonly number[];
  /* THE HEIGHT IS A DATA ATTRIBUTE, NOT A STYLE: "style-src-attr none"
     refuses "style="height: 62%"", so each sample is rounded to one of eleven
     buckets and "app.css" carries a rule per bucket. */
  bucket = (v: number) => Math.round(Math.max(0, Math.min(1, v)) * 10);
}

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-track-row',
  standalone: true,
  imports: [CommonModule, RouterLink, ClockComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.Default,
  template: `
    <div class="track-row" [attr.data-track]="track.id" [attr.data-current]="current ? '' : null">
      <span class="track-row__index">{{ index ?? track.trackNumber }}</span>
      <span class="track-row__text">
        <a class="track-row__title link" [routerLink]="path(route.track(track.id))">{{ track.title }}</a>
        <span class="track-row__meta" *ngIf="showArtist">
          <a *ngIf="artist" class="link" [routerLink]="path(route.artist(artist.handle))">{{ artist.name }}</a>
        </span>
      </span>
      <span class="track-row__album" *ngIf="showAlbum">
        <a *ngIf="album" class="link" [routerLink]="path(route.album(album.slug))">{{ album.title }}</a>
      </span>
      <span class="track-row__time"><awc-clock [seconds]="track.durationSec" /></span>
      <span class="row">
        <!-- "toggle" + "selected"; the FILL comes from the font axis in
             "app.css", because the Outlined face draws both ligature names the
             same and swapping the name alone changes nothing. -->
        <md-icon-button
          class="track-row__like"
          toggle=""
          [attr.selected]="liked ? '' : null"
          [attr.icon]="liked ? 'favorite' : 'favorite_border'"
          size="sm"
          [attr.data-liked]="liked ? '' : null"
          [attr.aria-label]="t(liked ? 'music.action.unlike' : 'music.action.like') + ': ' + track.title"
          (click)="player.toggleLike(track)"
        ></md-icon-button>
        <md-icon-button
          class="track-row__play"
          [attr.icon]="current && player.transport().state === 'playing' ? 'pause' : 'play_arrow'"
          size="sm"
          [attr.aria-label]="t('music.action.play') + ': ' + track.title"
          (click)="current ? player.toggle() : player.play(track)"
        ></md-icon-button>
      </span>
    </div>
  `,
})
export class TrackRowComponent {
  private readonly showcase = inject(ShowcaseService);
  readonly player = inject(PlayerService);
  readonly route = route;

  @Input({ required: true }) track!: Track;
  @Input() index?: number;
  @Input() showArtist = true;
  @Input() showAlbum = false;

  get current() { return this.player.transport().trackId === this.track.id; }
  get liked() { return this.player.likedFor(this.track); }
  get artist(): Artist | null { return artistById(this.track.artistId); }
  get album(): Album | null { return albumById(this.track.albumId); }

  t = (key: string) => this.showcase.t(key);
  /* `routerLink` with `appPath()`: Angular's router matches unslashed paths
     while the kit's `route.*` produces slashed ones, and `appPath` is the one
     place that conversion happens. */
  path = (to: string) => appPath(to);
}

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-track-list',
  standalone: true,
  imports: [CommonModule, TrackRowComponent],
  changeDetection: ChangeDetectionStrategy.Default,
  /* The COLUMN COUNT lives on the list, not the row: rows in one list must all
     use the same grid template or the durations form a ragged edge. */
  template: `<div class="track-list" [attr.data-albums]="showAlbum ? '' : null">
    <awc-track-row
      *ngFor="let track of tracks; let at = index"
      [track]="track"
      [index]="numbered ? track.trackNumber : at + 1"
      [showArtist]="showArtist"
      [showAlbum]="showAlbum"
    />
  </div>`,
})
export class TrackListComponent {
  @Input({ required: true }) tracks!: readonly Track[];
  @Input() numbered = false;
  @Input() showArtist = true;
  @Input() showAlbum = false;
}

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-album-card',
  standalone: true,
  imports: [RouterLink, ArtComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<a class="shelf-card" [routerLink]="path">
    <awc-art [art]="album.art" className="shelf-card__art" />
    <span class="shelf-card__title">{{ album.title }}</span>
    <span class="shelf-card__meta">{{ artistName }}</span>
  </a>`,
})
export class AlbumCardComponent {
  private readonly showcase = inject(ShowcaseService);
  @Input({ required: true }) album!: Album;
  get path() { return appPath(route.album(this.album.slug)); }
  get artistName() { return artistById(this.album.artistId)?.name ?? ''; }
}

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-playlist-card',
  standalone: true,
  imports: [RouterLink, ArtComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<a class="shelf-card" [routerLink]="path">
    <awc-art [art]="playlist.art" className="shelf-card__art shelf-card__art--wide" />
    <span class="shelf-card__title">{{ playlist.title }}</span>
    <span class="shelf-card__meta">{{ meta }}</span>
  </a>`,
})
export class PlaylistCardComponent {
  private readonly showcase = inject(ShowcaseService);
  @Input({ required: true }) playlist!: Playlist;
  get path() { return appPath(route.library()); }
  get meta() {
    return this.showcase.t('music.count.tracks', {
      count: this.showcase.t.formatNumber(this.playlist.trackIds.length),
    });
  }
}

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-artist-row',
  standalone: true,
  imports: [RouterLink, ArtComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<a class="artist-row" [routerLink]="path">
    <awc-art [art]="artist.art" className="artist-row__art" />
    <span class="track-row__text">
      <span class="track-row__title">{{ artist.name }}</span>
      <span class="track-row__meta">{{ listeners }}</span>
    </span>
  </a>`,
})
export class ArtistRowComponent {
  private readonly showcase = inject(ShowcaseService);
  @Input({ required: true }) artist!: Artist;
  get path() { return appPath(route.artist(this.artist.handle)); }
  get listeners() {
    return this.showcase.t('music.label.listeners', {
      count: this.showcase.t.formatNumber(this.artist.monthlyListeners, {
        notation: 'compact',
        maximumFractionDigits: 1,
      }),
    });
  }
}

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-volume-readout',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<span class="strip__readout">{{ text }}</span>`,
})
export class VolumeReadoutComponent {
  private readonly showcase = inject(ShowcaseService);
  @Input({ required: true }) volume!: number;
  /* `volumeDb()` returns null at zero rather than `-Infinity`: a fader all the
     way down reads "Silent". */
  get text() {
    const db = volumeDb(this.volume);
    return db === null
      ? this.showcase.t('music.label.silent')
      : this.showcase.t('music.label.decibels', {
          value: this.showcase.t.formatNumber(db, { maximumFractionDigits: 1 }),
        });
  }
}

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-pan-readout',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<span class="strip__readout">{{ text }}</span>`,
})
export class PanReadoutComponent {
  private readonly showcase = inject(ShowcaseService);
  @Input({ required: true }) pan!: number;
  /* A side and an amount, never a signed number: "L 0" and "R 0" are both
     wrong, and a build formatting a signed float produces one of them. */
  get text() {
    const position = panPosition(this.pan);
    if (position.side === 'centre') return this.showcase.t('music.label.panCentre');
    return this.showcase.t(
      position.side === 'left' ? 'music.label.panLeft' : 'music.label.panRight',
      { amount: this.showcase.t.formatNumber(position.amount) },
    );
  }
}

@Component({
  /* `:host { display: contents }` — the Angular host must be transparent to
     layout, or it becomes a box between a grid and the element that was meant
     to be its child. A shelf of album cards would lay out the HOSTS, not the
     cards, and the parity check reads it as a different document. */
  styles: ':host { display: contents; }',
  selector: 'awc-date-text',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<time [attr.datetime]="at">{{ text }}</time>`,
})
export class DateTextComponent {
  private readonly showcase = inject(ShowcaseService);
  @Input({ required: true }) at!: string;
  get text() { return this.showcase.t.formatDate(this.at.slice(0, 10), 'medium'); }
}
