// apps/showcase/social/svelte/src/lib/bits/StateChip.svelte
<!-- Every chip in the app resolves its label and colour the same way. -->
<script lang="ts">
  import { t } from '$lib/showcase';

  export let labelKey: string;
  export let color: string | undefined = undefined;
  export let icon: string | undefined = undefined;
  export let appearance = 'outlined';
</script>

<md-chip variant="assist" {appearance} {color} {icon} label={$t(labelKey)}></md-chip>

// apps/showcase/social/vue/src/components/bits/StateChip.vue
<!-- Every chip in the app resolves its label and colour the same way. -->
<script setup lang="ts">
import { useT } from '~/composables/useShowcase';

withDefaults(
  defineProps<{ labelKey: string; color?: string; icon?: string; appearance?: string }>(),
  { appearance: 'outlined' },
);
const t = useT();
</script>

<template>
  <md-chip
    variant="assist"
    :appearance="appearance"
    :color="color"
    :icon="icon"
    :label="t(labelKey)"
  ></md-chip>
</template>
