// apps/showcase/music/svelte/src/lib/screens/ArtistScreen.svelte
<script lang="ts">
  import { artistAlbums, artistByHandle, artistTopTracks } from '@awc-ui/showcase-kit/music';
  import { t } from '$lib/showcase';
  import { player, followedFor, toggleFollow } from '$lib/player';
  import { say } from '$lib/snackbar';
  import Screen from '$lib/components/Screen.svelte';
  import Panel from '$lib/components/Panel.svelte';
  import Count from '$lib/bits/Count.svelte';
  import Art from '$lib/bits/Art.svelte';
  import TrackList from '$lib/bits/TrackList.svelte';
  import AlbumCard from '$lib/bits/AlbumCard.svelte';
  import NotFoundScreen from '$lib/screens/NotFoundScreen.svelte';
  import ReleaseSkeleton from '$lib/skeletons/ReleaseSkeleton.svelte';

  export let handle: string;
  $: artist = artistByHandle(handle);
  $: albums = artist ? artistAlbums(artist) : [];
  $: top = artist ? artistTopTracks(artist) : [];
  $: followed = artist ? followedFor($player, artist.handle, artist.followed) : false;
</script>

{#if !artist}
  <NotFoundScreen />
{:else}
  <Screen title={artist.name} subtitle={$t('music.screen.artist.subtitle')} crumbLabel={artist.name}>
    <Count slot="aside" value={albums.length} />
    <ReleaseSkeleton slot="skeleton" />

    <div class="stack">
      <Panel>
        <div class="release-head">
          <Art art={artist.art} className="release-head__art" eager />
          <div class="release-head__text">
            <h2 class="release-head__title">{artist.name}</h2>
            <p class="person-row__meta">{$t('music.label.listeners', {
              count: $t.formatNumber(artist.monthlyListeners, { notation: 'compact', maximumFractionDigits: 1 }),
            })}</p>
            <p>{$t(artist.bioKey)}</p>
            <div class="row">
              <md-button
                class="artist__follow"
                variant={followed ? 'outlined' : 'filled'}
                icon={followed ? 'check' : 'person_add'}
                data-followed={followed ? '' : undefined}
                on:click={() => {
                  const was = followed;
                  if (artist) toggleFollow(artist.handle, artist.followed);
                  say(was ? 'music.msg.unfollowed' : 'music.msg.followed', { name: artist?.name ?? '' });
                }}
              >{$t(followed ? 'music.action.unfollow' : 'music.action.follow')}</md-button>
            </div>
          </div>
        </div>
      </Panel>

      <Panel title={$t('music.panel.topTracks')}>
        <Count slot="actions" value={top.length} />
        <TrackList tracks={top} showArtist={false} showAlbum />
      </Panel>

      <Panel title={$t('music.panel.discography')}>
        <Count slot="actions" value={albums.length} />
        <div class="shelf">{#each albums as album (album.id)}<AlbumCard {album} />{/each}</div>
      </Panel>
    </div>
  </Screen>
{/if}

// apps/showcase/music/vue/src/components/screens/ArtistScreen.vue
<script setup lang="ts">
import { computed } from 'vue';
import { artistAlbums, artistByHandle, artistTopTracks } from '@awc-ui/showcase-kit/music';
import { useT } from '~/composables/useShowcase';
import { usePlayer } from '~/composables/usePlayer';
import { useSnackbar } from '~/components/screens/useSnackbar';
import Screen from '~/components/Screen.vue';
import Panel from '~/components/Panel.vue';
import Count from '~/components/bits/Count.vue';
import Art from '~/components/bits/Art.vue';
import TrackList from '~/components/bits/TrackList.vue';
import AlbumCard from '~/components/bits/AlbumCard.vue';
import NotFoundScreen from '~/components/screens/NotFoundScreen.vue';
import ReleaseSkeleton from '~/components/skeletons/ReleaseSkeleton.vue';

const props = defineProps<{ handle: string }>();
const t = useT();
const player = usePlayer();
const { say } = useSnackbar();

const artist = computed(() => artistByHandle(props.handle));
const albums = computed(() => (artist.value ? artistAlbums(artist.value) : []));
const top = computed(() => (artist.value ? artistTopTracks(artist.value) : []));
const followed = computed(() =>
  artist.value ? player.followedFor(artist.value.handle, artist.value.followed) : false,
);
</script>

<template>
  <NotFoundScreen v-if="!artist" />
  <Screen v-else :title="artist.name" :subtitle="t('music.screen.artist.subtitle')" :crumb-label="artist.name">
    <template #aside><Count :value="albums.length" /></template>
    <template #skeleton><ReleaseSkeleton /></template>

    <div class="stack">
      <Panel>
        <div class="release-head">
          <Art :art="artist.art" class-name="release-head__art" eager />
          <div class="release-head__text">
            <h2 class="release-head__title">{{ artist.name }}</h2>
            <p class="person-row__meta">{{
              t('music.label.listeners', {
                count: t.formatNumber(artist.monthlyListeners, { notation: 'compact', maximumFractionDigits: 1 }),
              })
            }}</p>
            <p>{{ t(artist.bioKey) }}</p>
            <div class="row">
              <md-button
                class="artist__follow"
                :variant="followed ? 'outlined' : 'filled'"
                :icon="followed ? 'check' : 'person_add'"
                :data-followed="followed ? '' : undefined"
                @click="
                  player.toggleFollow(artist.handle, artist.followed);
                  say(followed ? 'music.msg.unfollowed' : 'music.msg.followed', { name: artist.name });
                "
              >{{ t(followed ? 'music.action.unfollow' : 'music.action.follow') }}</md-button>
            </div>
          </div>
        </div>
      </Panel>

      <Panel :title="t('music.panel.topTracks')">
        <template #actions><Count :value="top.length" /></template>
        <TrackList :tracks="top" :show-artist="false" show-album />
      </Panel>

      <Panel :title="t('music.panel.discography')">
        <template #actions><Count :value="albums.length" /></template>
        <div class="shelf"><AlbumCard v-for="a in albums" :key="a.id" :album="a" /></div>
      </Panel>
    </div>
  </Screen>
</template>
