// apps/showcase/music/react/src/components/screens/EmptyState.tsx
/** The one empty state, so five screens cannot each draw a different one. */
export function EmptyState({ message, hint }: { message: string; hint?: string }) {
  return (
    <div className="empty">
      <span className="material-symbols-outlined empty__icon" aria-hidden="true">
        music_off
      </span>
      <p className="empty__message">{message}</p>
      {hint ? <p className="empty__hint">{hint}</p> : null}
    </div>
  );
}

// apps/showcase/music/vue/src/components/screens/EmptyState.vue
<script setup lang="ts">
defineProps<{ message: string; hint?: string }>();
</script>
<template>
  <div class="empty">
    <span class="material-symbols-outlined empty__icon" aria-hidden="true">music_off</span>
    <p class="empty__message">{{ message }}</p>
    <p v-if="hint" class="empty__hint">{{ hint }}</p>
  </div>
</template>
