// apps/showcase/music/svelte/src/lib/screens/HomeScreen.svelte
<!--
  Home — the shelves are shelves, not a feed: a set of short scannable rows the
  reader recognises, each answering a different question.
-->
<script lang="ts">
  import { followedArtists, getTotals, ownPlaylists, recentAlbums, topTracks } from '@awc-ui/showcase-kit/music';
  import { t } from '$lib/showcase';
  import ListeningRoom from '$lib/components/ListeningRoom.svelte';
  import Screen from '$lib/components/Screen.svelte';
  import Panel from '$lib/components/Panel.svelte';
  import Count from '$lib/bits/Count.svelte';
  import TrackList from '$lib/bits/TrackList.svelte';
  import AlbumCard from '$lib/bits/AlbumCard.svelte';
  import PlaylistCard from '$lib/bits/PlaylistCard.svelte';
  import ArtistRow from '$lib/bits/ArtistRow.svelte';
  import HomeSkeleton from '$lib/skeletons/HomeSkeleton.svelte';

  const totals = getTotals();
  const tracks = topTracks(6);
  const albums = recentAlbums(6);
  const playlists = ownPlaylists().slice(0, 4);
  const artists = followedArtists().slice(0, 4);
</script>

<Screen title={$t('music.screen.home.title')} subtitle={$t('music.screen.home.subtitle')}>
  <Count slot="aside" value={totals.tracks} />
  <HomeSkeleton slot="skeleton" />

  <div class="stack music-home">
    <ListeningRoom />
    <Panel title={$t('music.panel.topTracks')}>
      <Count slot="actions" value={tracks.length} />
      <TrackList {tracks} showAlbum />
    </Panel>

    <Panel title={$t('music.panel.recent')}>
      <Count slot="actions" value={albums.length} />
      <div class="shelf">{#each albums as album (album.id)}<AlbumCard {album} />{/each}</div>
    </Panel>

    <Panel title={$t('music.panel.yourPlaylists')}>
      <Count slot="actions" value={playlists.length} />
      <div class="shelf">{#each playlists as playlist (playlist.id)}<PlaylistCard {playlist} />{/each}</div>
    </Panel>

    <Panel title={$t('music.panel.artists')}>
      <Count slot="actions" value={artists.length} />
      <div class="stack">{#each artists as artist (artist.id)}<ArtistRow {artist} />{/each}</div>
    </Panel>
  </div>
</Screen>

// apps/showcase/music/vue/src/components/screens/HomeScreen.vue
<!--
  Home — what the reader has been playing and what is new.

  THE SHELVES ARE SHELVES, not a feed. A music home page is a set of short,
  scannable rows the reader recognises, each answering a different question.
-->
<script setup lang="ts">
import {
  followedArtists,
  getTotals,
  ownPlaylists,
  recentAlbums,
  topTracks,
} from '@awc-ui/showcase-kit/music';
import { useT } from '~/composables/useShowcase';
import ListeningRoom from '~/components/ListeningRoom.vue';
import Screen from '~/components/Screen.vue';
import Panel from '~/components/Panel.vue';
import Count from '~/components/bits/Count.vue';
import TrackList from '~/components/bits/TrackList.vue';
import AlbumCard from '~/components/bits/AlbumCard.vue';
import PlaylistCard from '~/components/bits/PlaylistCard.vue';
import ArtistRow from '~/components/bits/ArtistRow.vue';
import HomeSkeleton from '~/components/skeletons/HomeSkeleton.vue';

const t = useT();
const totals = getTotals();
const tracks = topTracks(6);
const albums = recentAlbums(6);
const playlists = ownPlaylists().slice(0, 4);
const artists = followedArtists().slice(0, 4);
</script>

<template>
  <Screen :title="t('music.screen.home.title')" :subtitle="t('music.screen.home.subtitle')">
    <template #aside><Count :value="totals.tracks" /></template>
    <template #skeleton><HomeSkeleton /></template>

    <div class="stack music-home">
      <ListeningRoom />
      <Panel :title="t('music.panel.topTracks')">
        <template #actions><Count :value="tracks.length" /></template>
        <TrackList :tracks="tracks" show-album />
      </Panel>

      <Panel :title="t('music.panel.recent')">
        <template #actions><Count :value="albums.length" /></template>
        <div class="shelf"><AlbumCard v-for="a in albums" :key="a.id" :album="a" /></div>
      </Panel>

      <Panel :title="t('music.panel.yourPlaylists')">
        <template #actions><Count :value="playlists.length" /></template>
        <div class="shelf"><PlaylistCard v-for="p in playlists" :key="p.id" :playlist="p" /></div>
      </Panel>

      <Panel :title="t('music.panel.artists')">
        <template #actions><Count :value="artists.length" /></template>
        <div class="stack"><ArtistRow v-for="a in artists" :key="a.id" :artist="a" /></div>
      </Panel>
    </div>
  </Screen>
</template>
