// apps/showcase/music/react/src/components/screens/HomeScreen.tsx
/**
 * Home — what the reader has been playing and what is new.
 *
 * THE SHELVES ARE HORIZONTAL SHELVES, not a feed. A music home page is a set of
 * short, scannable rows the reader recognises, and each one answers a different
 * question: what do I play most, what is new, what have I made. A single
 * infinite list would be the Corvus feed with album covers on it.
 */

import {
  followedArtists,
  getTotals,
  ownPlaylists,
  recentAlbums,
  topTracks,
} from '@awc-ui/showcase-kit/music';
import { ListeningRoom } from '@/components/ListeningRoom';
import { Panel, Screen } from '@/components/Shell';
import { AlbumCard, ArtistRow, Count, PlaylistCard, TrackList } from '@/components/bits';
import { useT } from '@/lib/showcase';
import { HomeSkeleton } from '@/components/skeletons';

export function HomeScreen() {
  const t = useT();
  const totals = getTotals();
  const tracks = topTracks(6);
  const albums = recentAlbums(6);
  const playlists = ownPlaylists().slice(0, 4);
  const artists = followedArtists().slice(0, 4);

  return (
    <Screen
      title={t('music.screen.home.title')}
      subtitle={t('music.screen.home.subtitle')}
      aside={<Count value={totals.tracks} />}
      skeleton={<HomeSkeleton />}
    >
      <div className="stack music-home">
        <ListeningRoom />
        <Panel title={t('music.panel.topTracks')} actions={<Count value={tracks.length} />}>
          <TrackList tracks={tracks} showAlbum />
        </Panel>

        <Panel title={t('music.panel.recent')} actions={<Count value={albums.length} />}>
          <div className="shelf">
            {albums.map((album) => (
              <AlbumCard key={album.id} album={album} />
            ))}
          </div>
        </Panel>

        <Panel title={t('music.panel.yourPlaylists')} actions={<Count value={playlists.length} />}>
          <div className="shelf">
            {playlists.map((playlist) => (
              <PlaylistCard key={playlist.id} playlist={playlist} />
            ))}
          </div>
        </Panel>

        <Panel title={t('music.panel.artists')} actions={<Count value={artists.length} />}>
          <div className="stack">
            {artists.map((artist) => (
              <ArtistRow key={artist.id} artist={artist} />
            ))}
          </div>
        </Panel>
      </div>
    </Screen>
  );
}

// apps/showcase/music/vue/src/components/screens/HomeScreen.vue
<!--
  Home — what the reader has been playing and what is new.

  THE SHELVES ARE SHELVES, not a feed. A music home page is a set of short,
  scannable rows the reader recognises, each answering a different question.
-->
<script setup lang="ts">
import {
  followedArtists,
  getTotals,
  ownPlaylists,
  recentAlbums,
  topTracks,
} from '@awc-ui/showcase-kit/music';
import { useT } from '~/composables/useShowcase';
import ListeningRoom from '~/components/ListeningRoom.vue';
import Screen from '~/components/Screen.vue';
import Panel from '~/components/Panel.vue';
import Count from '~/components/bits/Count.vue';
import TrackList from '~/components/bits/TrackList.vue';
import AlbumCard from '~/components/bits/AlbumCard.vue';
import PlaylistCard from '~/components/bits/PlaylistCard.vue';
import ArtistRow from '~/components/bits/ArtistRow.vue';
import HomeSkeleton from '~/components/skeletons/HomeSkeleton.vue';

const t = useT();
const totals = getTotals();
const tracks = topTracks(6);
const albums = recentAlbums(6);
const playlists = ownPlaylists().slice(0, 4);
const artists = followedArtists().slice(0, 4);
</script>

<template>
  <Screen :title="t('music.screen.home.title')" :subtitle="t('music.screen.home.subtitle')">
    <template #aside><Count :value="totals.tracks" /></template>
    <template #skeleton><HomeSkeleton /></template>

    <div class="stack music-home">
      <ListeningRoom />
      <Panel :title="t('music.panel.topTracks')">
        <template #actions><Count :value="tracks.length" /></template>
        <TrackList :tracks="tracks" show-album />
      </Panel>

      <Panel :title="t('music.panel.recent')">
        <template #actions><Count :value="albums.length" /></template>
        <div class="shelf"><AlbumCard v-for="a in albums" :key="a.id" :album="a" /></div>
      </Panel>

      <Panel :title="t('music.panel.yourPlaylists')">
        <template #actions><Count :value="playlists.length" /></template>
        <div class="shelf"><PlaylistCard v-for="p in playlists" :key="p.id" :playlist="p" /></div>
      </Panel>

      <Panel :title="t('music.panel.artists')">
        <template #actions><Count :value="artists.length" /></template>
        <div class="stack"><ArtistRow v-for="a in artists" :key="a.id" :artist="a" /></div>
      </Panel>
    </div>
  </Screen>
</template>
