// apps/showcase/music/react/src/components/screens/LibraryScreen.tsx
/**
 * Library — everything the reader has saved.
 *
 * FOUR SECTIONS ORDERED BY HOW OFTEN THEY ARE OPENED, not alphabetically:
 * liked tracks first because that is the list people actually live in, then
 * their own playlists, then followed playlists, then albums.
 */

import {
  followedPlaylists,
  getAlbums,
  getTotals,
  getTracks,
  ownPlaylists,
} from '@awc-ui/showcase-kit/music';
import { Panel, Screen } from '@/components/Shell';
import { AlbumCard, Count, PlaylistCard, TrackList } from '@/components/bits';
import { EmptyState } from '@/components/screens/EmptyState';
import { usePlayer } from '@/lib/player';
import { useT } from '@/lib/showcase';
import { LibrarySkeleton } from '@/components/skeletons';

export function LibraryScreen() {
  const t = useT();
  const totals = getTotals();
  const player = usePlayer();
  const liked = getTracks().filter(player.likedFor);
  const own = ownPlaylists();
  const followed = followedPlaylists();
  const albums = getAlbums();

  return (
    <Screen
      title={t('music.screen.library.title')}
      subtitle={t('music.screen.library.subtitle')}
      aside={<Count value={totals.tracks} />}
      skeleton={<LibrarySkeleton />}
    >
      <div className="stack">
        <Panel title={t('music.panel.liked')} actions={<Count value={liked.length} />}>
          {liked.length === 0 ? (
            <EmptyState message={t('music.empty.liked')} />
          ) : (
            <TrackList tracks={liked} showAlbum />
          )}
        </Panel>

        <Panel title={t('music.panel.yourPlaylists')} actions={<Count value={own.length} />}>
          <div className="shelf">
            {own.map((playlist) => (
              <PlaylistCard key={playlist.id} playlist={playlist} />
            ))}
          </div>
        </Panel>

        <Panel
          title={t('music.panel.followedPlaylists')}
          actions={<Count value={followed.length} />}
        >
          <div className="shelf">
            {followed.map((playlist) => (
              <PlaylistCard key={playlist.id} playlist={playlist} />
            ))}
          </div>
        </Panel>

        <Panel title={t('music.panel.albums')} actions={<Count value={albums.length} />}>
          <div className="shelf">
            {albums.map((album) => (
              <AlbumCard key={album.id} album={album} />
            ))}
          </div>
        </Panel>
      </div>
    </Screen>
  );
}

// apps/showcase/music/vue/src/components/screens/LibraryScreen.vue
<!--
  Library — four sections ordered by how often they are opened, not
  alphabetically: liked tracks first, because that is the list people live in.
-->
<script setup lang="ts">
import { computed } from 'vue';
import { usePlayer } from '~/composables/usePlayer';
import {
  followedPlaylists,
  getAlbums,
  getTotals,
  getTracks,
  ownPlaylists,
} from '@awc-ui/showcase-kit/music';
import { useT } from '~/composables/useShowcase';
import Screen from '~/components/Screen.vue';
import Panel from '~/components/Panel.vue';
import Count from '~/components/bits/Count.vue';
import TrackList from '~/components/bits/TrackList.vue';
import AlbumCard from '~/components/bits/AlbumCard.vue';
import PlaylistCard from '~/components/bits/PlaylistCard.vue';
import EmptyState from '~/components/screens/EmptyState.vue';
import LibrarySkeleton from '~/components/skeletons/LibrarySkeleton.vue';

const t = useT();
const totals = getTotals();
const player = usePlayer();
const liked = computed(() => getTracks().filter(player.likedFor));
const own = ownPlaylists();
const followed = followedPlaylists();
const albums = getAlbums();
</script>

<template>
  <Screen :title="t('music.screen.library.title')" :subtitle="t('music.screen.library.subtitle')">
    <template #aside><Count :value="totals.tracks" /></template>
    <template #skeleton><LibrarySkeleton /></template>

    <div class="stack">
      <Panel :title="t('music.panel.liked')">
        <template #actions><Count :value="liked.length" /></template>
        <EmptyState v-if="liked.length === 0" :message="t('music.empty.liked')" />
        <TrackList v-else :tracks="liked" show-album />
      </Panel>

      <Panel :title="t('music.panel.yourPlaylists')">
        <template #actions><Count :value="own.length" /></template>
        <div class="shelf"><PlaylistCard v-for="p in own" :key="p.id" :playlist="p" /></div>
      </Panel>

      <Panel :title="t('music.panel.followedPlaylists')">
        <template #actions><Count :value="followed.length" /></template>
        <div class="shelf"><PlaylistCard v-for="p in followed" :key="p.id" :playlist="p" /></div>
      </Panel>

      <Panel :title="t('music.panel.albums')">
        <template #actions><Count :value="albums.length" /></template>
        <div class="shelf"><AlbumCard v-for="a in albums" :key="a.id" :album="a" /></div>
      </Panel>
    </div>
  </Screen>
</template>
