// apps/showcase/music/react/src/components/screens/ProfileScreen.tsx
/**
 * Profile — the reader's own listening, playlists and projects.
 *
 * IT ALSO CARRIES THE QUEUE, which is the one place in the app the whole of it
 * is visible. The transport shows what is loaded; this shows what follows, and
 * marks the row that is playing — the same `data-current` the track lists use,
 * so a reader recognises it.
 */

import {
  getTotals,
  getViewer,
  likedTracks,
  ownPlaylists,
  getProjects,
  trackById,
  artistById,
  upNext,
} from '@awc-ui/showcase-kit/music';
import { Panel, Screen } from '@/components/Shell';
import { Art, Count, PlaylistCard, TrackList } from '@/components/bits';
import { EmptyState } from '@/components/screens/EmptyState';
import { Link } from '@/lib/router';
import { route, withBase } from '@/lib/routes';
import { useT } from '@/lib/showcase';
import { usePlayer } from '@/lib/player';
import { ProfileSkeleton } from '@/components/skeletons';

export function ProfileScreen() {
  const t = useT();
  const player = usePlayer();
  const viewer = getViewer();
  const totals = getTotals();
  const liked = likedTracks(6);
  const playlists = ownPlaylists();
  const projects = getProjects();

  /* The whole remaining queue, not the transport's five-row preview. */
  const queue = upNext(player.transport, 50);

  return (
    <Screen
      title={t('music.screen.profile.title')}
      subtitle={t('music.screen.profile.subtitle')}
      aside={<Count value={totals.likedTracks} />}
      skeleton={<ProfileSkeleton />}
    >
      <div className="stack">
        <Panel>
          <div className="release-head">
            <Art art={viewer.art} className="release-head__art" eager />
            <div className="release-head__text">
              <h2 className="release-head__title">{viewer.displayName}</h2>
              <p className="person-row__meta">@{viewer.handle}</p>
              <div className="stat-row">
                <div>
                  <dt>{t('music.panel.liked')}</dt>
                  <dd>
                    <Count value={totals.likedTracks} />
                  </dd>
                </div>
                <div>
                  <dt>{t('music.panel.yourPlaylists')}</dt>
                  <dd>
                    <Count value={playlists.length} />
                  </dd>
                </div>
                <div>
                  <dt>{t('music.panel.projects')}</dt>
                  <dd>
                    <Count value={totals.projects} />
                  </dd>
                </div>
                <div>
                  <dt>{t('music.label.minutes')}</dt>
                  <dd>
                    <Count value={totals.listeningMinutes} compact />
                  </dd>
                </div>
              </div>
            </div>
          </div>
        </Panel>

        <Panel title={t('music.panel.queue')} actions={<Count value={queue.length} />}>
          {queue.length === 0 ? (
            <EmptyState message={t('music.empty.queue')} />
          ) : (
            <div className="stack">
              {queue.map((id, at) => {
                const track = trackById(id);
                if (!track) return null;
                return (
                  <div className="queue-row" key={id}>
                    <span className="queue-row__index">{at + 1}</span>
                    <span className="track-row__text">
                      <Link className="track-row__title link" href={withBase(route.track(track.id))}>
                        {track.title}
                      </Link>
                      <span className="track-row__meta">{artistById(track.artistId)?.name}</span>
                    </span>
                  </div>
                );
              })}
            </div>
          )}
        </Panel>

        <Panel title={t('music.panel.liked')} actions={<Count value={liked.length} />}>
          {liked.length === 0 ? (
            <EmptyState message={t('music.empty.liked')} />
          ) : (
            <TrackList tracks={liked} showAlbum />
          )}
        </Panel>

        <Panel title={t('music.panel.yourPlaylists')} actions={<Count value={playlists.length} />}>
          <div className="shelf">
            {playlists.map((playlist) => (
              <PlaylistCard key={playlist.id} playlist={playlist} />
            ))}
          </div>
        </Panel>

        <Panel title={t('music.panel.projects')} actions={<Count value={projects.length} />}>
          <div className="stack">
            {projects.map((project) => (
              <Link
                className="project-card"
                key={project.id}
                href={withBase(route.project(project.slug))}
              >
                <Art art={project.art} className="project-card__art" />
                <span className="project-card__text">
                  <span className="track-row__title">{project.title}</span>
                  <span className="track-row__meta">{t(project.stateKey)}</span>
                </span>
              </Link>
            ))}
          </div>
        </Panel>
      </div>
    </Screen>
  );
}

// apps/showcase/music/vue/src/components/screens/ProfileScreen.vue
<!--
  Profile — the reader's own listening, playlists and projects.

  IT ALSO CARRIES THE QUEUE, the one place the whole of it is visible: the
  transport shows what is loaded, this shows what follows.
-->
<script setup lang="ts">
import { computed } from 'vue';
import {
  artistById,
  getProjects,
  getTotals,
  getViewer,
  likedTracks,
  ownPlaylists,
  trackById,
  upNext,
} from '@awc-ui/showcase-kit/music';
import { useT } from '~/composables/useShowcase';
import { usePlayer } from '~/composables/usePlayer';
import { route, withBase } from '~/lib/routes';
import Screen from '~/components/Screen.vue';
import Panel from '~/components/Panel.vue';
import Count from '~/components/bits/Count.vue';
import Art from '~/components/bits/Art.vue';
import TrackList from '~/components/bits/TrackList.vue';
import PlaylistCard from '~/components/bits/PlaylistCard.vue';
import EmptyState from '~/components/screens/EmptyState.vue';
import ProfileSkeleton from '~/components/skeletons/ProfileSkeleton.vue';
import Drill from '~/components/Drill.vue';

const t = useT();
const player = usePlayer();
const viewer = getViewer();
const totals = getTotals();
const liked = likedTracks(6);
const playlists = ownPlaylists();
const projects = getProjects();

/* The whole remaining queue, not the transport's five-row preview. */
const queue = computed(() =>
  upNext(player.transport.value, 50)
    .map((id) => trackById(id))
    .filter((x): x is NonNullable<typeof x> => x !== null),
);
</script>

<template>
  <Screen :title="t('music.screen.profile.title')" :subtitle="t('music.screen.profile.subtitle')">
    <template #aside><Count :value="totals.likedTracks" /></template>
    <template #skeleton><ProfileSkeleton /></template>

    <div class="stack">
      <Panel>
        <div class="release-head">
          <Art :art="viewer.art" class-name="release-head__art" eager />
          <div class="release-head__text">
            <h2 class="release-head__title">{{ viewer.displayName }}</h2>
            <p class="person-row__meta">@{{ viewer.handle }}</p>
            <div class="stat-row">
              <div><dt>{{ t('music.panel.liked') }}</dt><dd><Count :value="totals.likedTracks" /></dd></div>
              <div><dt>{{ t('music.panel.yourPlaylists') }}</dt><dd><Count :value="playlists.length" /></dd></div>
              <div><dt>{{ t('music.panel.projects') }}</dt><dd><Count :value="totals.projects" /></dd></div>
              <div><dt>{{ t('music.label.minutes') }}</dt><dd><Count :value="totals.listeningMinutes" compact /></dd></div>
            </div>
          </div>
        </div>
      </Panel>

      <Panel :title="t('music.panel.queue')">
        <template #actions><Count :value="queue.length" /></template>
        <EmptyState v-if="queue.length === 0" :message="t('music.empty.queue')" />
        <div v-else class="stack">
          <div v-for="(track, at) in queue" :key="track.id" class="queue-row">
            <span class="queue-row__index">{{ at + 1 }}</span>
            <span class="track-row__text">
              <Drill link-class="track-row__title link" :to="route.track(track.id)">{{ track.title }}</Drill>
              <span class="track-row__meta">{{ artistById(track.artistId)?.name }}</span>
            </span>
          </div>
        </div>
      </Panel>

      <Panel :title="t('music.panel.liked')">
        <template #actions><Count :value="liked.length" /></template>
        <EmptyState v-if="liked.length === 0" :message="t('music.empty.liked')" />
        <TrackList v-else :tracks="liked" show-album />
      </Panel>

      <Panel :title="t('music.panel.yourPlaylists')">
        <template #actions><Count :value="playlists.length" /></template>
        <div class="shelf"><PlaylistCard v-for="p in playlists" :key="p.id" :playlist="p" /></div>
      </Panel>

      <Panel :title="t('music.panel.projects')">
        <template #actions><Count :value="projects.length" /></template>
        <div class="stack">
          <Drill v-for="p in projects" :key="p.id" link-class="project-card" :to="route.project(p.slug)">
            <Art :art="p.art" class-name="project-card__art" />
            <span class="project-card__text">
              <span class="track-row__title">{{ p.title }}</span>
              <span class="track-row__meta">{{ t(p.stateKey) }}</span>
            </span>
          </Drill>
        </div>
      </Panel>
    </div>
  </Screen>
</template>
