// apps/showcase/design/svelte/src/lib/components/SnackbarHost.svelte
<script lang="ts">
  import { t } from '$lib/showcase';
  import { snackbar, closeSnackbar } from '$lib/snackbar';
</script>

<md-snackbar
  class="app-snackbar"
  open={$snackbar !== null || undefined}
  message={$snackbar ? $t($snackbar.key, $snackbar.params) : ''}
  duration={4000}
  on:mdClose={closeSnackbar}
></md-snackbar>

// apps/showcase/music/vue/src/components/screens/SnackbarHost.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useT } from '~/composables/useShowcase';
import { useSnackbar } from '~/components/screens/useSnackbar';

const t = useT();
const { message, close } = useSnackbar();
const text = computed(() => (message.value ? t.value(message.value.key, message.value.params) : ''));
</script>

<template>
  <md-snackbar
    class="app-snackbar"
    :open="message !== null || undefined"
    :message="text"
    :duration="4000"
    @mdClose="close()"
  />
</template>
