// apps/showcase/banking/svelte/src/lib/skeletons/ScreenSkeleton.svelte
<!--
  The shape a screen gets when it has not described its own.

  IT IS NOT THE COMMON CASE, and that is the point. Every real screen passes
  its own measured `skeleton` slot to `<Screen>`, because "a KPI row and two
  panels" is none of their real layouts. What is left on this fallback is the
  not-found screen and the household guard — pages with nothing much to stand
  in for. Treat a screen reaching this as one that has not been measured yet.
-->
<script lang="ts">
  import KpiSkeleton from './KpiSkeleton.svelte';
  import PanelSkeleton from './PanelSkeleton.svelte';

  export let kpis = 4;
  export let panels = 2;
  export let label: string | undefined = undefined;
</script>

{#if kpis > 0}
  <section class="kpi-grid">
    {#each Array.from({ length: kpis }) as _, i (i)}
      <KpiSkeleton announce={i === 0} {label} />
    {/each}
  </section>
{/if}

<section class="grid-2">
  {#each Array.from({ length: panels }) as _, i (i)}
    <PanelSkeleton lines={8} />
  {/each}
</section>

// apps/showcase/social/vue/src/components/skeletons/ScreenSkeleton.vue
<!--
  The shape a screen gets when it has not described its own.

  IT IS NOT THE COMMON CASE, and that is the point. In the React source every
  one of the six screens passes its own measured `skeleton` to `<Screen>`,
  because "a KPI row and two panels" was never any of their real layouts. What
  is left on this fallback is the not-found screen and the household guard —
  pages with nothing much to stand in for — plus the stub screens until the
  screens phase lands its measured ones.

  So treat a screen reaching this as one that has not been measured yet.
  Exactly ONE shape announces (role=status on the first KPI's label bar), with
  the screen name.
-->
<script setup lang="ts">
import KpiSkeleton from './KpiSkeleton.vue';
import PanelSkeleton from './PanelSkeleton.vue';

withDefaults(defineProps<{ kpis?: number; panels?: number; label?: string }>(), {
  kpis: 4,
  panels: 2,
});
</script>

<template>
  <section v-if="kpis > 0" class="kpi-grid">
    <KpiSkeleton v-for="i in kpis" :key="i" :announce="i === 1" :label="label" />
  </section>

  <section class="grid-2">
    <PanelSkeleton v-for="i in panels" :key="i" :lines="8" />
  </section>
</template>
