// apps/showcase/music/vue/src/components/skeletons/ProjectListSkeleton.vue
<script setup lang="ts">
import SkeletonBar from './SkeletonBar.vue';
import SkeletonLine from './SkeletonLine.vue';
defineProps<{ count: number }>();
</script>
<template>
  <div class="stack">
    <div v-for="i in count" :key="i" class="project-card">
      <SkeletonBar width="64px" height="64px" radius="8px" />
      <div class="track-row__text">
        <SkeletonLine w="30%" :h="20" />
        <SkeletonLine w="18%" :h="16" />
      </div>
    </div>
  </div>
</template>

// apps/showcase/music/svelte/src/lib/skeletons/ProjectListSkeleton.svelte
<script lang="ts">
  import SkelBar from './SkelBar.svelte';
  import SkelLine from './SkelLine.svelte';
  export let count: number;
</script>
<div class="stack">
  {#each Array(count) as _, i (i)}
    <div class="project-card">
      <SkelBar width="64px" height="64px" radius="8px" />
      <div class="track-row__text"><SkelLine w="30%" h={20} /><SkelLine w="18%" h={16} /></div>
    </div>
  {/each}
</div>
