// apps/showcase/banking/vue/src/components/screens/TransactionsScreen.vue
<!--
  The statement — every movement across every account.

  GROUPED BY DAY, NOT PAGED. A statement is read by day: the heading is what
  lets someone find "that Tuesday", and it carries the day's net so nobody adds
  six rows up by eye. Paging would cut a day across a boundary, which is the one
  place a statement must not break.

  A STATEMENT HAS A PERIOD. The default is the reporting month — the whole
  twelve months is 652 rows and ~990 custom elements, which is a data dump
  rather than a statement. The period is a facet like the others, so the year
  is one chip away.

  ON A PHONE THE FILTERS COLLAPSE. Open, they are the entire first screen with
  no transaction visible until you scroll past controls for a list you have not
  seen.
-->
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  REPORTING_MONTH,
  getAccounts,
  getCategorySpend,
  getMonthlyFlow,
  getTransactions,
  statementDays,
  type Category,
  type TransactionStatus,
} from '@awc-ui/showcase-kit/banking';
import { useT } from '~/composables/useShowcase';
import { PHONE, useMediaQuery } from '~/lib/media';
import Screen from '~/components/Screen.vue';
import Panel from '~/components/Panel.vue';
import EmptyState from '~/components/EmptyState.vue';
import Count from '~/components/bits/Count.vue';
import Flow from '~/components/bits/Flow.vue';
import DateText from '~/components/bits/DateText.vue';
import StatementRow from '~/components/bits/StatementRow.vue';
import TransactionsFilters from './TransactionsFilters.vue';

/** `reverted` is too rare to earn a chip. */
const STATUSES: TransactionStatus[] = ['completed', 'pending', 'declined'];
const ALL_MONTHS = 'all';

const t = useT();
const phone = useMediaQuery(PHONE);

const month = ref<string>(REPORTING_MONTH);
const accountId = ref<string | null>(null);
const category = ref<Category | null>(null);
const status = ref<TransactionStatus | null>(null);
const search = ref('');

const accounts = getAccounts();
/* Built from the whole month's categories, not the filtered set, so the chips
   do not disappear as soon as one is chosen. */
const categories = getCategorySpend();
/* Newest first — the six months a reader might plausibly scroll back to. */
const months = getMonthlyFlow().map((m) => m.month).reverse().slice(0, 6);
const total = getTransactions().length;

const rows = computed(() =>
  getTransactions({
    month: month.value === ALL_MONTHS ? undefined : month.value,
    accountId: accountId.value ?? undefined,
    category: category.value ?? undefined,
    status: status.value ?? undefined,
    search: search.value,
  }),
);

const days = computed(() => statementDays(rows.value));

const filtered = computed(
  () =>
    month.value !== REPORTING_MONTH ||
    accountId.value !== null ||
    category.value !== null ||
    status.value !== null ||
    search.value !== '',
);

const activeCount = computed(
  () =>
    (month.value === REPORTING_MONTH ? 0 : 1) +
    (accountId.value ? 1 : 0) +
    (category.value ? 1 : 0) +
    (status.value ? 1 : 0) +
    (search.value ? 1 : 0),
);

const clear = () => {
  month.value = REPORTING_MONTH;
  accountId.value = null;
  category.value = null;
  status.value = null;
  search.value = '';
};
</script>

<template>
  <Screen
    :title="t('banking.screen.transactions.title')"
    :subtitle="t('banking.screen.transactions.subtitle')"
  >
    <template #aside><Count :value="rows.length" /></template>

    <!--
      THE FILTERS COLLAPSE ON A PHONE. Open, they are four chip rows and a
      search bar — the whole first screen, with no transaction visible until
      the reader scrolls past controls for a list they have not seen yet.
      Behind a disclosure, the statement is what the screen opens on, and the
      header carries the count so a filtered list never looks like the whole
      one.
    -->
    <md-accordion v-if="phone" variant="outlined" heading-level="2">
      <md-accordion-item
        :headline="t('banking.action.filter')"
        icon="filter_list"
        :supporting-text="activeCount > 0 ? t('banking.common.showing', { shown: rows.length, total }) : undefined"
      >
        <TransactionsFilters
          v-model:month="month"
          v-model:account-id="accountId"
          v-model:category="category"
          v-model:status="status"
          v-model:search="search"
          :accounts="accounts"
          :categories="categories"
          :months="months"
          :all-months="ALL_MONTHS"
          :statuses="STATUSES"
          :shown="rows.length"
          :total="total"
          :filtered="filtered"
          @clear="clear"
        />
      </md-accordion-item>
    </md-accordion>

    <Panel v-else :title="t('banking.action.filter')">
      <TransactionsFilters
        v-model:month="month"
        v-model:account-id="accountId"
        v-model:category="category"
        v-model:status="status"
        v-model:search="search"
        :accounts="accounts"
        :categories="categories"
        :months="months"
        :all-months="ALL_MONTHS"
        :statuses="STATUSES"
        :shown="rows.length"
        :total="total"
        :filtered="filtered"
        @clear="clear"
      />
    </Panel>

    <EmptyState v-if="days.length === 0" :message="t('banking.empty.transactions')" hint />
    <Panel v-else>
      <div v-for="day in days" :key="day.date" class="stack">
        <div class="statement-day">
          <span><DateText :value="day.date" format="long" /></span>
          <Flow :value="day.netEur" />
        </div>
        <md-list
          :label="t.formatDate(day.date, 'long')"
          interaction-mode="multi-action"
          list-style="segmented"
        >
          <StatementRow v-for="txn in day.rows" :key="txn.id" :txn="txn" :show-date="false" />
        </md-list>
      </div>
    </Panel>
  </Screen>
</template>

// apps/showcase/banking/react/src/components/screens/TransactionsScreen.tsx
/**
 * The statement — every movement across every account.
 *
 * GROUPED BY DAY, NOT PAGED. A bank statement is read by day: the day header is
 * what lets someone find "that Tuesday", and it carries the day's net so the
 * reader does not have to add six rows up by eye. Paging would cut a day in
 * half across a page boundary, which is the one place a statement must not
 * break.
 *
 * FOUR FILTERS, ALL FROM THE KIT. Account, category, status and a search. Every
 * one is passed straight into `getTransactions()` — this screen holds the
 * chosen values and nothing else, so the filtering rule is the kit's and the
 * five ports cannot each implement it slightly differently.
 */

import { useMemo, useRef, useState } from 'react';
import {
  REPORTING_MONTH,
  getAccounts,
  getCategorySpend,
  getMonthlyFlow,
  getTransactions,
  statementDays,
  type Category,
  type TransactionStatus,
} from '@awc-ui/showcase-kit/banking';
import { useT } from '@/lib/showcase';
import { PHONE, useMediaQuery } from '@/lib/media';
import { useCustomEvent } from '../elements';
import { EmptyState, Panel, Screen } from '../Shell';
import { Count, Money } from '../bits';
import { StatementDayHeading, TransactionRow } from './StatementParts';

/** The statuses worth filtering to. `reverted` is too rare to earn a chip. */
const STATUSES: TransactionStatus[] = ['completed', 'pending', 'declined'];

/**
 * A STATEMENT HAS A PERIOD, and this screen defaults to one.
 *
 * Rendering the whole twelve months put 652 rows and ~990 custom elements on
 * the page at once — measured. That is not a statement, it is a data dump: no
 * bank shows you a year by default, and every one of those rows is an element
 * the runtime has to upgrade before the screen settles. The month is a filter
 * like the other three, so widening it back out to everything is one chip
 * away and the reader is told how many rows that is.
 */
const ALL_MONTHS = 'all';

export function TransactionsScreen() {
  const t = useT();
  const phone = useMediaQuery(PHONE);

  const [month, setMonth] = useState<string>(REPORTING_MONTH);
  const [accountId, setAccountId] = useState<string | null>(null);
  const [category, setCategory] = useState<Category | null>(null);
  const [status, setStatus] = useState<TransactionStatus | null>(null);
  const [search, setSearch] = useState('');

  const accounts = getAccounts();
  /* The facet row is built from the WHOLE month's categories, not the filtered
     set, so the chips do not disappear as soon as one of them is chosen. */
  const categories = getCategorySpend();

  /* Newest first — the six months a reader might plausibly scroll back to,
     not all twelve, and the flow series already knows which months exist. */
  const months = useMemo(() => getMonthlyFlow().map((m) => m.month).reverse().slice(0, 6), []);

  const rows = useMemo(
    () =>
      getTransactions({
        month: month === ALL_MONTHS ? undefined : month,
        accountId: accountId ?? undefined,
        category: category ?? undefined,
        status: status ?? undefined,
        search,
      }),
    [month, accountId, category, status, search],
  );

  const days = useMemo(() => statementDays(rows), [rows]);
  const total = getTransactions().length;
  const filtered =
    month !== REPORTING_MONTH ||
    accountId !== null ||
    category !== null ||
    status !== null ||
    search !== '';

  const searchRef = useRef<HTMLElement | null>(null);
  useCustomEvent<CustomEvent<{ value: string }>>(searchRef, 'mdSearch', (event) =>
    setSearch(event.detail?.value ?? ''),
  );

  const monthRef = useRef<HTMLDivElement | null>(null);
  useCustomEvent<CustomEvent<{ selected: boolean }>>(monthRef, 'mdSelect', (event) => {
    const value = (event.target as HTMLElement | null)?.dataset?.month;
    // No deselect branch: a statement is always OF something, so pressing the
    // month that is already chosen leaves it chosen.
    if (value) setMonth(value);
  });

  const accountRef = useRef<HTMLDivElement | null>(null);
  useCustomEvent<CustomEvent<{ selected: boolean }>>(accountRef, 'mdSelect', (event) => {
    const value = (event.target as HTMLElement | null)?.dataset?.account;
    if (!value) return;
    setAccountId(event.detail.selected ? value : null);
  });

  const categoryRef = useRef<HTMLDivElement | null>(null);
  useCustomEvent<CustomEvent<{ selected: boolean }>>(categoryRef, 'mdSelect', (event) => {
    const value = (event.target as HTMLElement | null)?.dataset?.category as Category | undefined;
    if (!value) return;
    setCategory(event.detail.selected ? value : null);
  });

  const statusRef = useRef<HTMLDivElement | null>(null);
  useCustomEvent<CustomEvent<{ selected: boolean }>>(statusRef, 'mdSelect', (event) => {
    const value = (event.target as HTMLElement | null)?.dataset?.status as
      | TransactionStatus
      | undefined;
    if (!value) return;
    setStatus(event.detail.selected ? value : null);
  });

  /* What the collapsed phone header says, so a reader knows the list is
     filtered without opening the panel. */
  const activeCount =
    (month === REPORTING_MONTH ? 0 : 1) +
    (accountId ? 1 : 0) +
    (category ? 1 : 0) +
    (status ? 1 : 0) +
    (search ? 1 : 0);

  const clear = () => {
    setMonth(REPORTING_MONTH);
    setAccountId(null);
    setCategory(null);
    setStatus(null);
    setSearch('');
  };

  return (
    <Screen
      title={t('banking.screen.transactions.title')}
      subtitle={t('banking.screen.transactions.subtitle')}
      aside={<Count value={rows.length} />}
    >
      {/*
        THE FILTERS COLLAPSE ON A PHONE.
        Open, they are four chip rows and a search bar — the whole first screen,
        with no transaction visible until the reader scrolls past the controls
        for a list they have not seen yet. Behind a disclosure, the statement is
        what the screen opens on, and the header carries the count so a filtered
        list never looks like the whole one.
      */}
      {phone ? (
        <md-accordion variant="outlined" heading-level="2">
          <md-accordion-item
            headline={t('banking.action.filter')}
            icon="filter_list"
            supporting-text={
              activeCount > 0
                ? t('banking.common.showing', { shown: rows.length, total })
                : undefined
            }
          >
            <FilterBody />
          </md-accordion-item>
        </md-accordion>
      ) : (
        <Panel title={t('banking.action.filter')}>
          <FilterBody />
        </Panel>
      )}

      {days.length === 0 ? (
        <EmptyState message={t('banking.empty.transactions')} hint />
      ) : (
        <Panel>
          {days.map((day) => (
            <div key={day.date} className="stack">
              <StatementDayHeading date={day.date} netEur={day.netEur} />
              <md-list
                label={t.formatDate(day.date, 'long')}
                interaction-mode="multi-action"
                list-style="segmented"
              >
                {day.rows.map((txn) => (
                  <TransactionRow key={txn.id} txn={txn} showDate={false} />
                ))}
              </md-list>
            </div>
          ))}
        </Panel>
      )}
    </Screen>
  );

  /* Declared after the return it is used in, which is legal for a function
     declaration and keeps the screen's shape readable — the filter body is
     eighty lines of chips and would otherwise sit between the heading and the
     statement. */
  function FilterBody() {
    return (
        <div className="stack">
          {/* `trigger="bar"` and `full-width`: the default trigger is an icon
              that opens the field, which in a filter panel renders as a lone
              magnifying glass and reads as broken. */}
          <md-search
            ref={searchRef}
            layout="docked"
            trigger="bar"
            variant="contained"
            full-width
            debounce="250"
            label={t('banking.action.search')}
            placeholder={t('banking.table.merchant')}
            value={search}
          />

          {/* Four facet rows. The three below are single-select and a chip
              that is already on deselects when pressed again — `mdSelect`
              reports the new state, so the null branch is the deselect. The
              month row is different: it is a CHOICE, not a filter, so one is
              always on and pressing the current one does nothing. */}
          <div className="facet-row" ref={monthRef}>
            {months.map((value) => (
              <md-chip
                key={value}
                data-month={value}
                variant="filter"
                appearance="outlined"
                selected={month === value}
                label={t.formatDate(`${value}-01`, 'monthYear')}
              />
            ))}
            <md-chip
              data-month={ALL_MONTHS}
              variant="filter"
              appearance="outlined"
              selected={month === ALL_MONTHS}
              label={t('banking.common.all')}
            />
          </div>

          <div className="facet-row" ref={accountRef}>
            {accounts.map((account) => (
              <md-chip
                key={account.id}
                data-account={account.id}
                variant="filter"
                appearance="outlined"
                selected={accountId === account.id}
                label={account.nickname}
              />
            ))}
          </div>

          <div className="facet-row" ref={categoryRef}>
            {categories.map((row) => (
              <md-chip
                key={row.category}
                data-category={row.category}
                variant="filter"
                appearance="outlined"
                selected={category === row.category}
                label={t(row.categoryKey)}
              />
            ))}
          </div>

          <div className="facet-row" ref={statusRef}>
            {STATUSES.map((value) => (
              <md-chip
                key={value}
                data-status={value}
                variant="filter"
                appearance="outlined"
                selected={status === value}
                label={t(`banking.txnStatus.${value}`)}
              />
            ))}
            <span className="muted">
              {t('banking.common.showing', { shown: rows.length, total })}
            </span>
            {/* The clear button exists only while there is something to clear;
                a permanently-inert control in a filter bar is furniture. */}
            {filtered ? (
              <md-button variant="text" size="sm" icon="restart_alt" onClick={clear}>
                {t('banking.action.clearFilters')}
              </md-button>
            ) : null}
          </div>
        </div>
    );
  }
}
