// apps/showcase/credit-risk/next/app/facilities/[id]/page.tsx
/** `/facilities/[id]/` — 61 pages, one per committed line. */

import { getFacilities } from '@awc-ui/showcase-kit/data';
import { FacilityScreen } from '@/components/screens/FacilityScreen';

export const dynamicParams = false;

export function generateStaticParams() {
  return getFacilities().map((facility) => ({ id: facility.id }));
}

export default function Page({ params }: { params: { id: string } }) {
  return <FacilityScreen facilityId={params.id} />;
}

// apps/showcase/credit-risk/vue/pages/facilities/[id].vue
<!-- `/facilities/[id]/` — 61 pages, one per committed line. -->
<script setup lang="ts">
import FacilityScreen from '~/components/screens/FacilityScreen.vue';

const route = useRoute();
const facilityId = computed(() => String(route.params.id));
</script>

<template>
  <FacilityScreen :facility-id="facilityId" />
</template>
