// apps/showcase/credit-risk/react/app/counterparties/[id]/page.tsx
/** `/counterparties/[id]/` — 24 pages, one per obligor. */

import { getCounterparties } from '@awc-ui/showcase-kit/data';
import { CounterpartyScreen } from '@/components/screens/CounterpartyScreen';

export const dynamicParams = false;

export function generateStaticParams() {
  return getCounterparties().map((counterparty) => ({ id: counterparty.id }));
}

export default function Page({ params }: { params: { id: string } }) {
  return <CounterpartyScreen counterpartyId={params.id} />;
}

// apps/showcase/credit-risk/vue/pages/counterparties/[id].vue
<!-- `/counterparties/[id]/` — 24 pages, one per obligor. -->
<script setup lang="ts">
import CounterpartyScreen from '~/components/screens/CounterpartyScreen.vue';

const route = useRoute();
const counterpartyId = computed(() => String(route.params.id));
</script>

<template>
  <CounterpartyScreen :counterparty-id="counterpartyId" />
</template>
