// apps/showcase/design/svelte/src/App.svelte
<script lang="ts">
import {onDestroy} from 'svelte';import {model} from '$lib/document';import {pathname} from '$lib/router';import {route} from '$lib/routes';
import AppFrame from '$lib/components/AppFrame.svelte';import ProjectsScreen from '$lib/screens/ProjectsScreen.svelte';import ProjectScreen from '$lib/screens/ProjectScreen.svelte';import AssetsScreen from '$lib/screens/AssetsScreen.svelte';import AssetScreen from '$lib/screens/AssetScreen.svelte';import EditorScreen from '$lib/screens/EditorScreen.svelte';import ProfileScreen from '$lib/screens/ProfileScreen.svelte';import NotFoundScreen from '$lib/screens/NotFoundScreen.svelte';
$: project=/^\/p\/([^/]+)\/$/.exec($pathname);$: file=/^\/f\/([^/]+)\/$/.exec($pathname);$: asset=/^\/a\/([^/]+)\/$/.exec($pathname);
const decode=(value:string)=>{try{return decodeURIComponent(value)}catch{return ''}};
onDestroy(()=>model.dispose());
</script>
<AppFrame>{#if $pathname===route.projects()}<ProjectsScreen/>{:else if $pathname===route.editor()}<EditorScreen/>{:else if $pathname===route.assets()}<AssetsScreen/>{:else if $pathname===route.profile()}<ProfileScreen/>{:else if project}<ProjectScreen slug={decode(project[1])}/>{:else if file}<EditorScreen fileId={decode(file[1])}/>{:else if asset}<AssetScreen assetId={decode(asset[1])}/>{:else}<NotFoundScreen/>{/if}</AppFrame>

// apps/showcase/design/vue/src/App.vue
<script setup lang="ts">
import { computed } from "vue";
import { usePathname } from "~/lib/router";
import { route } from "~/lib/routes";
import AppFrame from "~/components/AppFrame.vue";
import ProjectsScreen from "~/components/screens/ProjectsScreen.vue";
import ProjectScreen from "~/components/screens/ProjectScreen.vue";
import EditorScreen from "~/components/screens/EditorScreen.vue";
import AssetsScreen from "~/components/screens/AssetsScreen.vue";
import AssetScreen from "~/components/screens/AssetScreen.vue";
import ProfileScreen from "~/components/screens/ProfileScreen.vue";
import NotFoundScreen from "~/components/screens/NotFoundScreen.vue";
const pathname = usePathname();
const resolved = computed(() => {
  const path = pathname.value;
  if (path === route.projects()) return { view: ProjectsScreen, props: {} };
  if (path === route.editor()) return { view: EditorScreen, props: {} };
  if (path === route.assets()) return { view: AssetsScreen, props: {} };
  if (path === route.profile()) return { view: ProfileScreen, props: {} };
  try {
    let match = /^\/p\/([^/]+)\/$/.exec(path);
    if (match)
      return {
        view: ProjectScreen,
        props: { slug: decodeURIComponent(match[1]) },
      };
    match = /^\/f\/([^/]+)\/$/.exec(path);
    if (match)
      return {
        view: EditorScreen,
        props: { fileId: decodeURIComponent(match[1]) },
      };
    match = /^\/a\/([^/]+)\/$/.exec(path);
    if (match)
      return {
        view: AssetScreen,
        props: { assetId: decodeURIComponent(match[1]) },
      };
  } catch {}
  return { view: NotFoundScreen, props: {} };
});
</script>
<template>
  <AppFrame
    ><component :is="resolved.view" v-bind="resolved.props" :key="pathname"
  /></AppFrame>
</template>
