// apps/showcase/wealth/react/src/components/bits.tsx
/**
 * The small, repeated pieces: formatted figures, the chips that carry a domain
 * state, the meters, and the KPI tile.
 *
 * Every one of them takes a domain value and resolves BOTH halves of it through
 * the kit: the COLOUR through the status maps in `@awc-ui/showcase-kit/wealth`,
 * the LABEL through the dictionary key that travels beside the value
 * (`household.strategyKey`, `goal.statusKey`, `order.sideKey`). Nothing here
 * contains English, so nothing here can render English into a translated page.
 *
 * THIS IS THE CONTRACT FOR SCREENS. If you are writing one of the six screens:
 *
 *   - Never call `Intl` and never call `toFixed`. Money goes through `<Money>`,
 *     ratios through `<Percent>`, signed figures through `<Signed>`, dates
 *     through `<DateText>`. They are pinned to the dock's locale and to UTC.
 *   - Never write `status === 'breach' ? 'error' : …`. Use the chip or the dot.
 *   - Never hardcode a chip's `color`. Every mapping is already in the kit.
 *   - A `…Key` field is a dictionary key, not a label. Pass it to `t()`.
 */

import type { CSSProperties, ReactNode } from 'react';
import {
  allocationColor,
  allocationDot,
  assetClassRole,
  driftColor,
  goalColor,
  goalDot,
  kycColor,
  kycDot,
  mandateColor,
  orderColor,
  orderDot,
  orderSideColor,
  plColor,
  priorityColor,
  proposalColor,
  riskProfileColor,
  riskToleranceColor,
  segmentColor,
  strategyColor,
  type AllocationStatus,
  type AssetClass,
  type Currency,
  type GoalStatus,
  type KycStatus,
  type Mandate,
  type OrderSide,
  type OrderStatus,
  type Priority,
  type ProposalStatus,
  type RiskProfile,
  type RiskTolerance,
  type Segment,
  type Strategy,
} from '@awc-ui/showcase-kit/wealth';
import { Link } from '@/lib/router';
import { useShowcase, useT } from '@/lib/showcase';
import { Sparkline } from './elements';

/* ------------------------------------------------------------- formatting */

/**
 * A money amount.
 *
 * `currency` defaults to EUR because every aggregate in the fixture is in EUR;
 * pass a position's or an order's own `currency` for a local amount. `compact`
 * gives €3.2m — the right choice for a KPI tile or a chart axis, the wrong one
 * for a table cell where the reader is comparing figures digit by digit.
 */
export function Money({
  value,
  currency = 'EUR',
  compact = false,
  digits,
}: {
  value: number;
  currency?: Currency | string;
  compact?: boolean;
  /** Force a fraction-digit count. Default: 0 standard, 1 compact. */
  digits?: number;
}) {
  const t = useT();
  // A SIGNED money figure is `<Signed>`, not a flag here: the kit's
  // CurrencyOptions has no `signDisplay`, so composing the `+` is a real piece
  // of work rather than one more option, and it belongs next to the colour
  // decision that goes with it.
  return (
    <span className="num">
      {t.formatCurrency(value, {
        currency,
        notation: compact ? 'compact' : 'standard',
        maximumFractionDigits: digits,
        minimumFractionDigits: digits,
      })}
    </span>
  );
}

/**
 * A ratio, as a percentage.
 *
 * The value is a FRACTION — `0.0135` renders as `1.35%`. Every ratio in the
 * fixture is stored that way, so pass it straight in and never multiply by 100
 * first.
 */
export function Percent({
  value,
  digits = 2,
  sign = false,
}: {
  value: number;
  digits?: number;
  /** Prefix a `+` on positives. Use it for drift, excess return and P/L. */
  sign?: boolean;
}) {
  const t = useT();
  return (
    <span className="num">
      {t.formatPercent(value, {
        maximumFractionDigits: digits,
        minimumFractionDigits: Math.min(digits, 1),
        signDisplay: sign ? 'exceptZero' : undefined,
      })}
    </span>
  );
}

/**
 * A signed figure — profit and loss, an excess return, a drift.
 *
 * THE COLOUR IS NEVER THE ONLY CARRIER. The sign is always in the text
 * (`signDisplay: 'exceptZero'`), and an optional glyph repeats it, so the cell
 * still says which way it went in monochrome, in a screenshot, and to a reader
 * who cannot distinguish the two hues. That is the WCAG 1.4.1 rule, and a
 * financial table is exactly where it gets broken.
 *
 * `plColor` has a dead band: a move smaller than the rounding scale is neither
 * green nor red, which is what stops a table of near-flat positions reading as
 * a chequerboard.
 */
export function Signed({
  value,
  kind = 'money',
  currency = 'EUR',
  compact = false,
  digits,
}: {
  value: number;
  /** `money` formats with a currency; `percent` treats the value as a fraction. */
  kind?: 'money' | 'percent';
  currency?: Currency | string;
  compact?: boolean;
  digits?: number;
}) {
  const t = useT();
  // The dead band is a fraction for percentages and a currency unit for money —
  // half a cent is not a move, but half a euro on a €40m book is not either.
  const color = plColor(value, kind === 'percent' ? 0.0005 : 1);
  const className = color === 'success' ? 'pl-up' : color === 'error' ? 'pl-down' : 'pl-flat';

  const text =
    kind === 'percent'
      ? t.formatPercent(value, {
          maximumFractionDigits: digits ?? 2,
          minimumFractionDigits: Math.min(digits ?? 2, 1),
          signDisplay: 'exceptZero',
        })
      : `${value > 0 ? '+' : ''}${t.formatCurrency(value, {
          currency,
          notation: compact ? 'compact' : 'standard',
          maximumFractionDigits: digits,
          minimumFractionDigits: digits,
        })}`;

  /*
   * `<bdi>`, NOT `<span>`, and this one was found by looking at the page.
   *
   * The money branch composes its `+` by hand, because the kit's
   * `CurrencyOptions` has no `signDisplay` to hand to `Intl`. A leading `+` is a
   * bidi-NEUTRAL character, so under `dir="rtl"` the algorithm resolves it
   * against the paragraph direction and moves it to the other end: `+€1.5m`
   * renders as `€1.5m+`, which reads as a different number. `<bdi>` isolates
   * the run and auto-detects its direction from its own first strong character,
   * so the sign stays where it was written. The percent branch does not need it
   * — `Intl` places that sign itself and gets the bidi right — but one wrapper
   * for both keeps the two from drifting.
   */
  return <bdi className={`num ${className}`}>{text}</bdi>;
}

/**
 * A count, as a small chip.
 *
 * This is what goes in a KPI tile's `trailing` slot and beside a panel title —
 * NOT `md-badge`. A badge has to sit on a host it can overlap, and dropped into
 * a card's foot it anchors to the card's corner and is clipped in half. A chip
 * is a standalone element that takes its own space, which is what a count in a
 * row of facts actually is.
 */
export function Count({ value, color = 'primary' }: { value: number; color?: string }) {
  const t = useT();
  return (
    <md-chip
      variant="assist"
      appearance="outlined"
      color={color}
      label={t.formatNumber(value, { maximumFractionDigits: 0 })}
    />
  );
}

/** A plain number: a quantity, a count, a basis-point figure. */
export function Num({ value, digits = 0 }: { value: number; digits?: number }) {
  const t = useT();
  return (
    <span className="num">
      {t.formatNumber(value, { maximumFractionDigits: digits, minimumFractionDigits: digits })}
    </span>
  );
}

/**
 * A calendar date.
 *
 * Rendered inside a `<time>` with a machine-readable `dateTime`, so the ISO
 * value survives even though the visible text is localised. `formatDate` is
 * pinned to UTC in the kit, so 2026-06-30 is 30 June west of Greenwich too.
 */
export function DateText({
  value,
  style = 'medium',
}: {
  value: string;
  style?: 'short' | 'medium' | 'long' | 'monthYear';
}) {
  const t = useT();
  return <time dateTime={value}>{t.formatDate(value, style)}</time>;
}

/** A full UTC instant from the audit trail. The date part is what is shown. */
export function TimestampText({ value }: { value: string }) {
  const t = useT();
  const date = value.slice(0, 10);
  return <time dateTime={value}>{t.formatDate(date, 'medium')}</time>;
}

/* ----------------------------------------------------------------- layout */

/** A `dt`/`dd` pair inside a `.dl` grid. */
export function Fact({ label, children }: { label: string; children: ReactNode }) {
  return (
    <div>
      <dt>{label}</dt>
      <dd>{children}</dd>
    </div>
  );
}

/** A drill link into the next screen down. Always an `<a>` with a real href. */
export function Drill({ href, children }: { href: string; children: ReactNode }) {
  return (
    <Link className="drill" href={href}>
      {children}
    </Link>
  );
}

/** A status dot beside a name, without the dot pushing the baseline around. */
export function NameCell({ dot, children }: { dot?: ReactNode; children: ReactNode }) {
  return (
    <span className="with-dot">
      {dot}
      <span>{children}</span>
    </span>
  );
}

/* -------------------------------------------------------- search highlight */

/**
 * The regex metacharacters, so a query can be dropped into a pattern.
 *
 * WITHOUT THIS, TYPING `(` THROWS. The query is whatever the reader has typed
 * so far, and half the punctuation on a keyboard is syntax to `RegExp`.
 * `$&` in the replacement is the character that matched, so each one comes back
 * escaped and matches itself literally.
 */
const REGEX_METACHARACTERS = /[.*+?^${}()|[\]\\]/g;

/**
 * The mark's colours are a CONTAINER/ON-CONTAINER PAIR, never a literal.
 *
 * The user-agent default for `<mark>` is black on yellow, which is a hardcoded
 * colour that survives into the dark theme and lands a light-mode highlight in
 * the middle of a dark table. A token pair is contrast-checked in both themes
 * and follows a re-themed palette. `tertiary` is the accent role this console
 * does not spend on a health state, so a hit reads as "this is what you asked
 * for" rather than as a warning about the row.
 *
 * The weight is a SECOND CARRIER. Colour alone would fail WCAG 1.4.1; the
 * `<mark>` element itself carries the same fact into the accessibility tree,
 * which is the whole reason it is `<mark>` and not a `<span class>`.
 */
const HIGHLIGHT_STYLE: CSSProperties = {
  background: 'var(--md-sys-color-tertiary-container)',
  color: 'var(--md-sys-color-on-tertiary-container)',
  fontWeight: 500,
  // Inline padding only: padding-block would grow the line box and shift the
  // baseline of the one cell in the row that happens to contain a match.
  paddingInline: '1px',
  borderRadius: 'var(--md-sys-shape-corner-extra-small)',
};

/**
 * The run of `text` a search query matched, wrapped in `<mark>`.
 *
 * FILTERING IS THE KIT'S; SHOWING WHY A ROW SURVIVED IS THE VIEW'S. The
 * selectors match case-insensitively on a TRIMMED query (`fold(search.trim())`
 * in `selectors.ts`), so this splits on the same trimmed needle with the `i`
 * flag — a table that highlighted a different substring from the one that kept
 * the row would be worse than no highlight at all.
 *
 * NEVER BUILT AS AN HTML STRING. Interpolating the query into markup and
 * setting `innerHTML` is an injection with a text field for a source, and the
 * fixture holds names with `&` and `.` that would break it even with a
 * co-operative reader. `split()` with ONE capture group returns the pieces as
 * strings and React makes the nodes: every match is escaped by construction,
 * and a query that occurs three times in one cell is marked three times.
 *
 * The kit matches its fields JOINED BY A SPACE, so a query that straddles two
 * of them ("VWCE Vanguard") keeps the row and marks nothing. That is the honest
 * outcome — no single cell contains that text.
 */
export function Highlight({ text, query }: { text: string; query?: string }) {
  const needle = query?.trim() ?? '';
  if (!needle) return <>{text}</>;

  const parts = text.split(
    new RegExp(`(${needle.replace(REGEX_METACHARACTERS, '\\$&')})`, 'gi'),
  );

  return (
    <>
      {parts.map((part, index) =>
        // One capture group makes the result alternate: even indices are the
        // text between matches, odd indices are the matches themselves.
        index % 2 === 1 ? (
          <mark key={index} style={HIGHLIGHT_STYLE}>
            {part}
          </mark>
        ) : (
          part
        ),
      )}
    </>
  );
}

/* --------------------------------------------------------------- KPI tile */

export function KpiTile({
  label,
  value,
  hint,
  trend,
  trendLabels,
  formatTrend,
  color = 'primary',
  trailing,
}: {
  label: string;
  value: ReactNode;
  hint?: ReactNode;
  /** Historical values for the sparkline, oldest first. */
  trend?: number[];
  /** Tooltip x labels — month ends, already formatted. */
  trendLabels?: string[];
  formatTrend?: (value: number | null) => string;
  /** One of the md colour roles. Use a `status.ts` map, not a guess. */
  color?: string;
  /**
   * A small node at the end of the foot row — a chip, a dot, a count.
   *
   * NOT a bare `md-badge`. A badge anchors absolutely against the nearest
   * POSITIONED ancestor and translates itself past that ancestor's corner, so
   * dropped in here it lands on the card's top-right corner and is sliced in
   * half by the card's own `overflow: hidden`. A badge needs a host to sit on
   * and a `.badge-anchor` wrapper around it; see the pattern in `app.css`.
   */
  trailing?: ReactNode;
}) {
  const { state } = useShowcase();
  return (
    <md-card variant="filled" full-width>
      <div className="kpi">
        <p className="kpi__label">{label}</p>
        <p className="kpi__value">{value}</p>
        {trend && trend.length > 1 ? (
          <div className="kpi__spark">
            <Sparkline
              data={trend}
              labels={trendLabels}
              valueFormatter={formatTrend}
              locale={state.locale}
              variant="area"
              color={color}
              curve="monotone"
              show-marks="extremes"
              height="34px"
            />
          </div>
        ) : null}
        {hint || trailing ? (
          <div className="kpi__foot">
            <span>{hint}</span>
            {trailing}
          </div>
        ) : null}
      </div>
    </md-card>
  );
}

/* ------------------------------------------------------------------ chips */

/**
 * The base every chip below is built from.
 *
 * `variant="assist"` throughout: these are informational, not filters and not
 * removable user input. A screen that wants a toggleable facet wants
 * `variant="filter"` and owns its own state.
 */
function StateChip({
  labelKey,
  color,
  appearance = 'filled',
  icon,
  title,
}: {
  labelKey: string;
  color: string;
  appearance?: 'filled' | 'outlined' | 'elevated';
  icon?: string;
  title?: string;
}) {
  const t = useT();
  return (
    <md-chip
      variant="assist"
      appearance={appearance}
      color={color}
      icon={icon}
      label={t(labelKey)}
      title={title}
    />
  );
}

export function StrategyChip({ strategy }: { strategy: Strategy }) {
  return <StateChip labelKey={`wealth.strategy.${strategy}`} color={strategyColor[strategy]} />;
}

export function MandateChip({ mandate }: { mandate: Mandate }) {
  return (
    <StateChip
      labelKey={`wealth.mandate.${mandate}`}
      color={mandateColor[mandate]}
      appearance="outlined"
    />
  );
}

export function SegmentChip({ segment }: { segment: Segment }) {
  return (
    <StateChip
      labelKey={`wealth.segment.${segment}`}
      color={segmentColor[segment]}
      appearance="outlined"
    />
  );
}

export function RiskProfileChip({ profile }: { profile: RiskProfile }) {
  return (
    <StateChip labelKey={`wealth.riskProfile.${profile}`} color={riskProfileColor[profile]} />
  );
}

export function RiskToleranceChip({ tolerance }: { tolerance: RiskTolerance }) {
  return (
    <StateChip
      labelKey={`wealth.riskTolerance.${tolerance}`}
      color={riskToleranceColor[tolerance]}
      appearance="outlined"
    />
  );
}

export function KycChip({ status }: { status: KycStatus }) {
  return <StateChip labelKey={`wealth.kycStatus.${status}`} color={kycColor[status]} />;
}

export function ClientRoleChip({ role }: { role: string }) {
  return <StateChip labelKey={`wealth.clientRole.${role}`} color="secondary" appearance="outlined" />;
}

export function AssetClassChip({ assetClass }: { assetClass: AssetClass }) {
  const t = useT();
  /*
   * Filled and tonal, driven by a ROLE NAME.
   *
   * This used to tint `--md-chip-outline-color` with the chart palette, on the
   * reasoning that an asset class is a category rather than a health state and
   * so has no semantic role. The category part is still true — equity is not
   * `success` — but the conclusion was wrong: `assetClassRole` names the same
   * palette entries the chart uses, and a role name is what buys the whole
   * family. One `var()` could only paint an outline; `color="primary"` gives
   * the chip a container AND a legible label on it, which is what makes a
   * filled chip possible at all. The donut slice and the chip stay the same
   * hue, one tonal and one full strength.
   *
   * `cash` resolves to `undefined` and takes the neutral surface treatment —
   * see the note on `assetClassRole` for why it has no role of its own.
   */
  return (
    <md-chip
      variant="assist"
      appearance="filled"
      color={assetClassRole[assetClass]}
      label={t(`wealth.assetClass.${assetClass}`)}
    />
  );
}

export function InstrumentTypeChip({ type }: { type: string }) {
  return <StateChip labelKey={`wealth.instrumentType.${type}`} color="info" appearance="outlined" />;
}

export function AllocationChip({ status }: { status: AllocationStatus }) {
  return (
    <StateChip labelKey={`wealth.allocationStatus.${status}`} color={allocationColor[status]} />
  );
}

export function GoalStatusChip({ status }: { status: GoalStatus }) {
  return <StateChip labelKey={`wealth.goalStatus.${status}`} color={goalColor[status]} />;
}

export function PriorityChip({ priority }: { priority: Priority }) {
  return (
    <StateChip
      labelKey={`wealth.priority.${priority}`}
      color={priorityColor[priority]}
      appearance="outlined"
    />
  );
}

export function ProposalStatusChip({ status }: { status: ProposalStatus }) {
  return <StateChip labelKey={`wealth.proposalStatus.${status}`} color={proposalColor[status]} />;
}

export function ProposalTypeChip({ type }: { type: string }) {
  return <StateChip labelKey={`wealth.proposalType.${type}`} color="secondary" appearance="outlined" />;
}

export function OrderStatusChip({ status }: { status: OrderStatus }) {
  return <StateChip labelKey={`wealth.orderStatus.${status}`} color={orderColor[status]} />;
}

/**
 * Buy or sell.
 *
 * Deliberately NOT green/red: `success` and `error` mean "went well" and "went
 * wrong" everywhere else in this console, and a sell is neither. The mapping is
 * in the kit and the reasoning with it.
 */
export function OrderSideChip({ side }: { side: OrderSide }) {
  return <StateChip labelKey={`wealth.orderSide.${side}`} color={orderSideColor[side]} />;
}

export function ActivityCategoryChip({ category }: { category: string }) {
  return (
    <StateChip
      labelKey={`wealth.activityCategory.${category}`}
      color="secondary"
      appearance="outlined"
    />
  );
}

/* ------------------------------------------------------------------- dots */

/**
 * Every dot below carries a `label`.
 *
 * `md-status-dot`'s colour is the only thing it renders, so an unlabelled one
 * leaves colour as the sole carrier of meaning — which is exactly the failure
 * the `label` prop exists to prevent. The only case for dropping it is a dot
 * sitting immediately beside a chip that already says the same word, where
 * naming both announces the state twice per row.
 */
export function KycDot({ status }: { status: KycStatus }) {
  const t = useT();
  return (
    <md-status-dot
      inline
      state={kycDot[status]}
      size="small"
      label={t(`wealth.kycStatus.${status}`)}
    />
  );
}

export function AllocationDot({ status }: { status: AllocationStatus }) {
  const t = useT();
  return (
    <md-status-dot
      inline
      state={allocationDot[status]}
      size="small"
      label={t(`wealth.allocationStatus.${status}`)}
    />
  );
}

export function GoalDot({ status }: { status: GoalStatus }) {
  const t = useT();
  return (
    <md-status-dot
      inline
      state={goalDot[status]}
      size="small"
      label={t(`wealth.goalStatus.${status}`)}
    />
  );
}

export function OrderDot({ status }: { status: OrderStatus }) {
  const t = useT();
  return (
    <md-status-dot
      inline
      state={orderDot[status]}
      size="small"
      label={t(`wealth.orderStatus.${status}`)}
    />
  );
}

/* ----------------------------------------------------------------- meters */

/**
 * A fraction against a cap, as a labelled linear meter.
 *
 * `md-meter` is for a read-only value in a known range — a funded percentage, a
 * weight, a coverage ratio. It is NOT a progress indicator: nothing here is
 * loading.
 */
export function RatioMeter({
  label,
  fraction,
  color,
  max = 1,
  thickness = 10,
}: {
  label: string;
  /** A fraction. Clamped into 0…`max` for the bar; the text keeps the real value. */
  fraction: number;
  color: string;
  max?: number;
  thickness?: number;
}) {
  const t = useT();
  return (
    <md-meter
      value={Math.max(0, Math.min(max, fraction)) * 100}
      min="0"
      max={max * 100}
      color={color}
      thickness={thickness}
      label={label}
      show-label
      show-value
      value-text={t.formatPercent(fraction, { maximumFractionDigits: 1 })}
    />
  );
}

/**
 * A goal's funded percentage.
 *
 * The bar is clamped at 100% but the TEXT is not, so an over-funded objective
 * reads "112%" beside a full bar rather than silently looking merely complete.
 */
export function FundedMeter({ fraction, status }: { fraction: number; status: GoalStatus }) {
  const t = useT();
  return (
    <md-meter
      value={Math.max(0, Math.min(1, fraction)) * 100}
      min="0"
      max="100"
      color={goalColor[status]}
      thickness="8"
      label={t('wealth.table.funded')}
      show-label
      show-value
      value-text={t.formatPercent(fraction, { maximumFractionDigits: 0 })}
    />
  );
}

/**
 * Allocation drift, as a meter.
 *
 * `drift` is a SIGNED fraction and can be negative — underweight. `md-meter`
 * has no negative range, so the bar shows the DISTANCE from target scaled into
 * 0…10 percentage points and the direction is carried by the colour, the
 * status chip and the signed text beside it. Reading the bar alone never says a
 * breached class is fine: at a breach the bar is full AND red.
 */
export function DriftMeter({ drift }: { drift: number }) {
  const t = useT();
  const distance = Math.abs(drift);
  return (
    <md-meter
      value={Math.min(10, distance * 100)}
      min="0"
      max="10"
      color={driftColor(drift)}
      thickness="8"
      label={t('wealth.table.drift')}
      show-label
      value-text={t.formatPercent(drift, { maximumFractionDigits: 1, signDisplay: 'exceptZero' })}
      show-value
    />
  );
}

// apps/showcase/wealth/angular/src/app/components/bits.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';
import {
  allocationColor,
  allocationDot,
  assetClassRole,
  driftColor,
  goalColor,
  goalDot,
  kycColor,
  kycDot,
  mandateColor,
  orderColor,
  orderDot,
  orderSideColor,
  plColor,
  priorityColor,
  proposalColor,
  riskProfileColor,
  riskToleranceColor,
  segmentColor,
  strategyColor,
  type AllocationStatus,
  type AssetClass,
  type GoalStatus,
  type KycStatus,
  type Mandate,
  type MdColor,
  type OrderSide,
  type OrderStatus,
  type Priority,
  type ProposalStatus,
  type RiskProfile,
  type RiskTolerance,
  type Segment,
  type Strategy,
} from '@awc-ui/showcase-kit/wealth';
import { ShowcaseComponent } from '../lib/screen.base';
import { SparklineComponent } from './sparkline.component';

/**
 * The small, repeated pieces: formatted figures, the chips that carry a domain
 * state, the dots, the meters, and the KPI tile.
 *
 * Every one of them takes a domain value and resolves BOTH halves of it through
 * the kit: the COLOUR through the status maps in `@awc-ui/showcase-kit/wealth`,
 * the LABEL through the dictionary key that travels beside the value
 * (`household.strategyKey`, `goal.statusKey`, `order.sideKey`). Nothing here
 * contains English, so nothing here can render English into a translated page.
 *
 * THIS IS THE CONTRACT FOR SCREENS. If you are writing one of the six screens:
 *
 *   - Never call `Intl` and never call `toFixed`. Money goes through
 *     `span[awcMoney]`, ratios through `span[awcPercent]`, signed figures
 *     through `bdi[awcSigned]`, dates through `time[awcDate]`. They are pinned
 *     to the dock's locale and to UTC.
 *   - Never write `status === 'breach' ? 'error' : …`. Use the chip or the dot.
 *   - Never hardcode a chip's `color`. Every mapping is already in the kit.
 *   - A `…Key` field is a dictionary key, not a label. Pass it to `t()`.
 *   - A drill link is the credit-risk Angular idiom, not a component:
 *     `<a class="drill" [routerLink]="appPath(route.household(id))">`.
 *
 * WHY ATTRIBUTE SELECTORS. The React build's bits are wrapperless — `<Money>`
 * IS a `<span class="num">`. An Angular component always renders its own host
 * element, so each of these takes an attribute selector and IS the element it
 * would otherwise wrap: the DOM a screen reader walks, the structural
 * selectors in `app.css` (`.dl > div`, `.with-dot > span`) and the parity
 * check's geometry all stay identical to the other builds'. Wrappers that
 * contain block layout (`KpiTile`, the meters) use `display: contents` hosts
 * instead, per the credit-risk precedent.
 */

/* ------------------------------------------------------------- formatting */

/**
 * A money amount, as `<span awcMoney [value]="x">`.
 *
 * `currency` defaults to EUR because every aggregate in the fixture is in EUR;
 * pass a position's or an order's own `currency` for a local amount. `compact`
 * gives €3.2m — the right choice for a KPI tile or a chart axis, the wrong one
 * for a table cell where the reader is comparing figures digit by digit.
 *
 * A SIGNED money figure is `bdi[awcSigned]`, not a flag here: the kit's
 * `CurrencyOptions` has no `signDisplay`, so composing the `+` is a real piece
 * of work rather than one more option, and it belongs next to the colour
 * decision that goes with it.
 */
@Component({
  selector: 'span[awcMoney]',
  standalone: true,
  host: { class: 'num' },
  template: '{{ text }}',
})
export class MoneyComponent extends ShowcaseComponent {
  @Input({ required: true }) value!: number;
  @Input() currency: string = 'EUR';
  @Input() compact = false;
  /** Force a fraction-digit count. Default: 0 standard, 1 compact. */
  @Input() digits?: number;

  protected get text(): string {
    return this.t.formatCurrency(this.value, {
      currency: this.currency,
      notation: this.compact ? 'compact' : 'standard',
      maximumFractionDigits: this.digits,
      minimumFractionDigits: this.digits,
    });
  }
}

/**
 * A ratio, as a percentage: `<span awcPercent [value]="x">`.
 *
 * The value is a FRACTION — `0.0135` renders as `1.35%`. Every ratio in the
 * fixture is stored that way, so pass it straight in and never multiply by 100
 * first.
 */
@Component({
  selector: 'span[awcPercent]',
  standalone: true,
  host: { class: 'num' },
  template: '{{ text }}',
})
export class PercentComponent extends ShowcaseComponent {
  @Input({ required: true }) value!: number;
  @Input() digits = 2;
  /** Prefix a `+` on positives. Use it for drift, excess return and P/L. */
  @Input() sign = false;

  protected get text(): string {
    return this.t.formatPercent(this.value, {
      maximumFractionDigits: this.digits,
      minimumFractionDigits: Math.min(this.digits, 1),
      signDisplay: this.sign ? 'exceptZero' : undefined,
    });
  }
}

/**
 * A signed figure — profit and loss, an excess return, a drift:
 * `<bdi awcSigned [value]="x">`.
 *
 * THE COLOUR IS NEVER THE ONLY CARRIER. The sign is always in the text, and the
 * cell still says which way it went in monochrome (WCAG 1.4.1). `plColor` has a
 * dead band: a move smaller than the rounding scale is neither green nor red.
 *
 * `<bdi>`, NOT `<span>`: the money branch composes its `+` by hand (the kit's
 * `CurrencyOptions` has no `signDisplay`), and a leading `+` is a bidi-NEUTRAL
 * character — under `dir="rtl"` it moves to the other end and `+€1.5m` renders
 * as `€1.5m+`, a different number. `<bdi>` isolates the run. The percent branch
 * does not need it — `Intl` places that sign itself — but one element for both
 * keeps the two from drifting.
 */
@Component({
  selector: 'bdi[awcSigned]',
  standalone: true,
  host: { '[class]': 'hostClass' },
  template: '{{ text }}',
})
export class SignedComponent extends ShowcaseComponent {
  @Input({ required: true }) value!: number;
  /** `money` formats with a currency; `percent` treats the value as a fraction. */
  @Input() kind: 'money' | 'percent' = 'money';
  @Input() currency: string = 'EUR';
  @Input() compact = false;
  @Input() digits?: number;

  protected get hostClass(): string {
    // The dead band is a fraction for percentages and a currency unit for
    // money — half a cent is not a move, but half a euro on a €40m book is not
    // either.
    const color = plColor(this.value, this.kind === 'percent' ? 0.0005 : 1);
    const state = color === 'success' ? 'pl-up' : color === 'error' ? 'pl-down' : 'pl-flat';
    return `num ${state}`;
  }

  protected get text(): string {
    if (this.kind === 'percent') {
      return this.t.formatPercent(this.value, {
        maximumFractionDigits: this.digits ?? 2,
        minimumFractionDigits: Math.min(this.digits ?? 2, 1),
        signDisplay: 'exceptZero',
      });
    }
    return `${this.value > 0 ? '+' : ''}${this.t.formatCurrency(this.value, {
      currency: this.currency,
      notation: this.compact ? 'compact' : 'standard',
      maximumFractionDigits: this.digits,
      minimumFractionDigits: this.digits,
    })}`;
  }
}

/** A plain number: a quantity, a count, a basis-point figure. */
@Component({
  selector: 'span[awcNum]',
  standalone: true,
  host: { class: 'num' },
  template: '{{ text }}',
})
export class NumComponent extends ShowcaseComponent {
  @Input({ required: true }) value!: number;
  @Input() digits = 0;

  protected get text(): string {
    return this.t.formatNumber(this.value, {
      maximumFractionDigits: this.digits,
      minimumFractionDigits: this.digits,
    });
  }
}

/**
 * A count, as a small chip: `<md-chip awcCount [value]="n">`.
 *
 * This is what goes in a KPI tile's foot and beside a panel title — NOT
 * `md-badge`. A badge has to sit on a host it can overlap, and dropped into a
 * card's foot it anchors to the card's corner and is clipped in half. A chip is
 * a standalone element that takes its own space, which is what a count in a row
 * of facts actually is.
 */
@Component({
  selector: 'md-chip[awcCount]',
  standalone: true,
  host: {
    variant: 'assist',
    appearance: 'outlined',
    '[attr.color]': 'color',
    '[attr.label]': 'label',
  },
  template: '',
})
export class CountComponent extends ShowcaseComponent {
  @Input({ required: true }) value!: number;
  @Input() color = 'primary';

  protected get label(): string {
    return this.t.formatNumber(this.value, { maximumFractionDigits: 0 });
  }
}

/**
 * A calendar date: `<time awcDate [value]="iso">`.
 *
 * The machine-readable `datetime` keeps the ISO value even though the visible
 * text is localised. `formatDate` is pinned to UTC in the kit, so 2026-06-30 is
 * 30 June west of Greenwich too.
 */
@Component({
  selector: 'time[awcDate]',
  standalone: true,
  host: { '[attr.datetime]': 'value' },
  template: '{{ text }}',
})
export class DateTextComponent extends ShowcaseComponent {
  @Input({ required: true }) value!: string;
  @Input() dateStyle: 'short' | 'medium' | 'long' | 'monthYear' = 'medium';

  protected get text(): string {
    return this.t.formatDate(this.value, this.dateStyle);
  }
}

/** A full UTC instant from the audit trail. The date part is what is shown. */
@Component({
  selector: 'time[awcTimestamp]',
  standalone: true,
  host: { '[attr.datetime]': 'value' },
  template: '{{ text }}',
})
export class TimestampTextComponent extends ShowcaseComponent {
  @Input({ required: true }) value!: string;

  protected get text(): string {
    return this.t.formatDate(this.value.slice(0, 10), 'medium');
  }
}

/* ----------------------------------------------------------------- layout */

/**
 * A `dt`/`dd` pair inside a `.dl` grid: `<div awcFact [label]="…">`.
 *
 * An ATTRIBUTE selector, so the component IS the `<div>` rather than wrapping
 * one. The shared stylesheet targets `.dl > div`, and that is a structural
 * selector — `display: contents` fixes layout but cannot make `.dl > div` match
 * `.dl > awc-fact > div`.
 */
@Component({
  selector: 'div[awcFact]',
  standalone: true,
  template: `
    <dt>{{ label }}</dt>
    <dd><ng-content /></dd>
  `,
})
export class FactComponent {
  @Input({ required: true }) label!: string;
}

/**
 * A status dot beside a name, without the dot pushing the baseline around:
 * `<span awcNameCell><md-status-dot dot awcDot … /> name</span>`.
 */
@Component({
  selector: 'span[awcNameCell]',
  standalone: true,
  host: { class: 'with-dot' },
  template: `
    <ng-content select="[dot]" />
    <span><ng-content /></span>
  `,
})
export class NameCellComponent {}

/* -------------------------------------------------------- search highlight */

/**
 * The regex metacharacters, so a query can be dropped into a pattern.
 * WITHOUT THIS, TYPING `(` THROWS — half the punctuation on a keyboard is
 * syntax to `RegExp`. `$&` in the replacement is the character that matched.
 */
const REGEX_METACHARACTERS = /[.*+?^${}()|[\]\\]/g;

/**
 * The run of `text` a search query matched, wrapped in `<mark>`.
 *
 * FILTERING IS THE KIT'S; SHOWING WHY A ROW SURVIVED IS THE VIEW'S. The
 * selectors match case-insensitively on a TRIMMED query, so this splits on the
 * same trimmed needle with the `i` flag. NEVER BUILT AS AN HTML STRING —
 * `split()` with ONE capture group returns the pieces as strings and the
 * template makes the nodes, so every match is escaped by construction.
 *
 * The mark's colours are a CONTAINER/ON-CONTAINER PAIR, never a literal: the
 * user-agent default (black on yellow) survives into the dark theme. `tertiary`
 * is the accent role this console does not spend on a health state. The
 * element being `<mark>` carries the same fact into the accessibility tree,
 * which is the second carrier WCAG 1.4.1 wants.
 */
@Component({
  selector: 'awc-highlight',
  standalone: true,
  styles: `
    :host {
      display: contents;
    }
    mark {
      background: var(--md-sys-color-tertiary-container);
      color: var(--md-sys-color-on-tertiary-container);
      font-weight: 500;
      /* Inline padding only: padding-block would grow the line box and shift
         the baseline of the one cell in the row that contains a match. */
      padding-inline: 1px;
      border-radius: var(--md-sys-shape-corner-extra-small);
    }
  `,
  template: `
    @for (part of parts; track $index) {
      @if ($index % 2 === 1) {
        <mark>{{ part }}</mark>
      } @else {
        {{ part }}
      }
    }
  `,
})
export class HighlightComponent {
  @Input({ required: true }) text!: string;
  @Input() query?: string;

  protected get parts(): string[] {
    const needle = this.query?.trim() ?? '';
    if (!needle) return [this.text];
    // One capture group makes the result alternate: even indices are the text
    // between matches, odd indices are the matches themselves.
    return this.text.split(
      new RegExp(`(${needle.replace(REGEX_METACHARACTERS, '\\$&')})`, 'gi'),
    );
  }
}

/* --------------------------------------------------------------- KPI tile */

/**
 * A KPI tile: label, figure, its own sparkline, and a footnote.
 *
 * `value` and `hint` are projected (`[value]`, `[hint]`) so a screen can put a
 * `span[awcMoney]` or `bdi[awcSigned]` inside them, exactly as the React build
 * passes nodes. `hasFoot` gates the foot row because Angular cannot ask whether
 * a slot received content — set it when passing `[hint]` or `[trailing]`.
 *
 * `[trailing]` must be a `md-chip[awcCount]`, never a bare `md-badge`: a badge
 * anchors absolutely against the nearest positioned ancestor and translates
 * itself past that ancestor's corner, so dropped in here it lands on the
 * card's top-right corner and is sliced in half by the card's own
 * `overflow: hidden`.
 */
@Component({
  selector: 'awc-kpi-tile',
  standalone: true,
  styles: ':host { display: contents; }',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [SparklineComponent],
  template: `
    <md-card variant="filled" full-width>
      <div class="kpi">
        <p class="kpi__label">{{ label }}</p>
        <p class="kpi__value"><ng-content select="[value]" /></p>
        @if (trend && trend.length > 1) {
          <div class="kpi__spark">
            <awc-sparkline
              [data]="trend"
              [labels]="trendLabels"
              [valueFormatter]="formatTrend"
              [color]="color"
            />
          </div>
        }
        @if (hasFoot) {
          <div class="kpi__foot">
            <span><ng-content select="[hint]" /></span>
            <ng-content select="[trailing]" />
          </div>
        }
      </div>
    </md-card>
  `,
})
export class KpiTileComponent {
  @Input({ required: true }) label!: string;
  /** Historical values for the sparkline, oldest first. */
  @Input() trend?: number[];
  /** Tooltip x labels — month ends, already formatted. */
  @Input() trendLabels?: string[];
  /** Build with `memo()` keyed on the locale — it closes over the translator. */
  @Input() formatTrend?: (value: number | null) => string;
  /** One of the md colour roles. Use a `status.ts` map, not a guess. */
  @Input() color = 'primary';
  /** Set when projecting `[hint]` or `[trailing]` content. */
  @Input() hasFoot = false;
}

/* ------------------------------------------------------------------ chips */

type ChipKind =
  | 'strategy'
  | 'mandate'
  | 'segment'
  | 'riskProfile'
  | 'riskTolerance'
  | 'kyc'
  | 'clientRole'
  | 'assetClass'
  | 'instrumentType'
  | 'allocation'
  | 'goal'
  | 'priority'
  | 'proposalStatus'
  | 'proposalType'
  | 'orderStatus'
  | 'orderSide'
  | 'activityCategory';

/**
 * Every state chip, in one component: `<md-chip awcChip kind="…" [value]="…">`.
 *
 * The React build has eighteen one-line chip components because a React
 * component is a function call; an Angular component is a decorated class, and
 * eighteen of them would be more ceremony than the thing they wrap — the same
 * trade the credit-risk Angular build made. The `kind` picks the kit colour
 * map, the appearance and the dictionary prefix; the value supplies the rest.
 *
 * `variant="assist"` throughout: these are informational, not filters and not
 * removable user input. A screen that wants a toggleable facet wants
 * `variant="filter"` and owns its own state.
 *
 * An ATTRIBUTE selector on `md-chip` itself, so this component IS the chip
 * rather than wrapping one — the DOM a screen reader walks stays identical to
 * the other builds', and a chip stays the SIBLING of the dot beside it.
 *
 * Appearance notes carried over from the React build: `mandate`, `segment`,
 * `riskTolerance`, `priority` and the two catalogue kinds are outlined so a row
 * holding two chips is not a wall of colour; `assetClass` is filled and tonal,
 * driven by `assetClassRole` — the same palette entries the donut uses, so the
 * slice and the chip stay the same hue (`cash` resolves to no role and takes
 * the neutral surface treatment); `orderSide` is deliberately NOT green/red —
 * `success` and `error` mean "went well" and "went wrong" everywhere else in
 * this console, and a sell is neither.
 */
@Component({
  selector: 'md-chip[awcChip]',
  standalone: true,
  host: {
    variant: 'assist',
    '[attr.appearance]': 'appearance',
    '[attr.color]': 'color',
    '[attr.label]': 'label',
    '[attr.icon]': 'icon ?? null',
    '[attr.title]': 'title ?? null',
  },
  template: '',
})
export class ChipComponent extends ShowcaseComponent {
  @Input({ required: true }) kind!: ChipKind;
  /** The domain value: a Strategy, KycStatus, OrderSide, … */
  @Input({ required: true }) value!: string;
  @Input() icon?: string;
  @Input() title?: string;

  private static readonly OUTLINED: readonly ChipKind[] = [
    'mandate',
    'segment',
    'riskTolerance',
    'clientRole',
    'instrumentType',
    'priority',
    'proposalType',
    'activityCategory',
  ];

  protected get appearance(): string {
    return ChipComponent.OUTLINED.includes(this.kind) ? 'outlined' : 'filled';
  }

  protected get color(): string | null {
    switch (this.kind) {
      case 'strategy':
        return strategyColor[this.value as Strategy];
      case 'mandate':
        return mandateColor[this.value as Mandate];
      case 'segment':
        return segmentColor[this.value as Segment];
      case 'riskProfile':
        return riskProfileColor[this.value as RiskProfile];
      case 'riskTolerance':
        return riskToleranceColor[this.value as RiskTolerance];
      case 'kyc':
        return kycColor[this.value as KycStatus];
      case 'clientRole':
        return 'secondary';
      case 'assetClass':
        return assetClassRole[this.value as AssetClass] ?? null;
      case 'instrumentType':
        return 'info';
      case 'allocation':
        return allocationColor[this.value as AllocationStatus];
      case 'goal':
        return goalColor[this.value as GoalStatus];
      case 'priority':
        return priorityColor[this.value as Priority];
      case 'proposalStatus':
        return proposalColor[this.value as ProposalStatus];
      case 'proposalType':
        return 'secondary';
      case 'orderStatus':
        return orderColor[this.value as OrderStatus];
      case 'orderSide':
        return orderSideColor[this.value as OrderSide];
      case 'activityCategory':
        return 'secondary';
    }
  }

  private static readonly KEY_PREFIX: Record<ChipKind, string> = {
    strategy: 'wealth.strategy',
    mandate: 'wealth.mandate',
    segment: 'wealth.segment',
    riskProfile: 'wealth.riskProfile',
    riskTolerance: 'wealth.riskTolerance',
    kyc: 'wealth.kycStatus',
    clientRole: 'wealth.clientRole',
    assetClass: 'wealth.assetClass',
    instrumentType: 'wealth.instrumentType',
    allocation: 'wealth.allocationStatus',
    goal: 'wealth.goalStatus',
    priority: 'wealth.priority',
    proposalStatus: 'wealth.proposalStatus',
    proposalType: 'wealth.proposalType',
    orderStatus: 'wealth.orderStatus',
    orderSide: 'wealth.orderSide',
    activityCategory: 'wealth.activityCategory',
  };

  protected get label(): string {
    return this.t(`${ChipComponent.KEY_PREFIX[this.kind]}.${this.value}`);
  }
}

/* ------------------------------------------------------------------- dots */

/**
 * The status dots: `<md-status-dot awcDot kind="…" [value]="…">`.
 *
 * Every dot here carries a `label`. `md-status-dot`'s colour is the only thing
 * it renders, so an unlabelled one leaves colour as the sole carrier of
 * meaning — which is exactly the failure the `label` prop exists to prevent.
 * The only case for dropping the label is a dot sitting immediately beside a
 * chip that already says the same word; none of the wealth dots does.
 *
 * `inline` on every one: without it `md-status-dot` is a block, and a dot set
 * beside a word sits on its own baseline a few pixels low.
 */
@Component({
  selector: 'md-status-dot[awcDot]',
  standalone: true,
  host: {
    inline: '',
    size: 'small',
    '[attr.state]': 'state',
    '[attr.label]': 'label',
  },
  template: '',
})
export class DotComponent extends ShowcaseComponent {
  @Input({ required: true }) kind!: 'kyc' | 'allocation' | 'goal' | 'order';
  @Input({ required: true }) value!: string;

  protected get state(): string {
    switch (this.kind) {
      case 'kyc':
        return kycDot[this.value as KycStatus];
      case 'allocation':
        return allocationDot[this.value as AllocationStatus];
      case 'goal':
        return goalDot[this.value as GoalStatus];
      case 'order':
        return orderDot[this.value as OrderStatus];
    }
  }

  protected get label(): string {
    const prefix = {
      kyc: 'wealth.kycStatus',
      allocation: 'wealth.allocationStatus',
      goal: 'wealth.goalStatus',
      order: 'wealth.orderStatus',
    }[this.kind];
    return this.t(`${prefix}.${this.value}`);
  }
}

/* ----------------------------------------------------------------- meters */

/**
 * A fraction against a cap, as a labelled linear meter.
 *
 * `md-meter` is for a read-only value in a known range — a funded percentage, a
 * weight, a coverage ratio. It is NOT a progress indicator: nothing here is
 * loading.
 */
@Component({
  selector: 'awc-ratio-meter',
  standalone: true,
  styles: ':host { display: contents; }',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <md-meter
      [attr.value]="clamped"
      min="0"
      [attr.max]="max * 100"
      [attr.color]="color"
      [attr.thickness]="thickness"
      [attr.label]="label"
      show-label
      show-value
      [attr.value-text]="t.formatPercent(fraction, { maximumFractionDigits: 1 })"
    ></md-meter>
  `,
})
export class RatioMeterComponent extends ShowcaseComponent {
  @Input({ required: true }) label!: string;
  /** A fraction. Clamped into 0…`max` for the bar; the text keeps the real value. */
  @Input({ required: true }) fraction!: number;
  @Input({ required: true }) color!: string;
  @Input() max = 1;
  @Input() thickness = 10;

  protected get clamped(): number {
    return Math.max(0, Math.min(this.max, this.fraction)) * 100;
  }
}

/**
 * A goal's funded percentage.
 *
 * The bar is clamped at 100% but the TEXT is not, so an over-funded objective
 * reads "112%" beside a full bar rather than silently looking merely complete.
 */
@Component({
  selector: 'awc-funded-meter',
  standalone: true,
  styles: ':host { display: contents; }',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <md-meter
      [attr.value]="clamped"
      min="0"
      max="100"
      [attr.color]="color"
      thickness="8"
      [attr.label]="t('wealth.table.funded')"
      show-label
      show-value
      [attr.value-text]="t.formatPercent(fraction, { maximumFractionDigits: 0 })"
    ></md-meter>
  `,
})
export class FundedMeterComponent extends ShowcaseComponent {
  @Input({ required: true }) fraction!: number;
  @Input({ required: true }) status!: GoalStatus;

  protected get clamped(): number {
    return Math.max(0, Math.min(1, this.fraction)) * 100;
  }

  protected get color(): MdColor {
    return goalColor[this.status];
  }
}

/**
 * Allocation drift, as a meter.
 *
 * `drift` is a SIGNED fraction and can be negative — underweight. `md-meter`
 * has no negative range, so the bar shows the DISTANCE from target scaled into
 * 0…10 percentage points and the direction is carried by the colour, the
 * status chip and the signed text beside it. Reading the bar alone never says a
 * breached class is fine: at a breach the bar is full AND red.
 */
@Component({
  selector: 'awc-drift-meter',
  standalone: true,
  styles: ':host { display: contents; }',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <md-meter
      [attr.value]="scaled"
      min="0"
      max="10"
      [attr.color]="color"
      thickness="8"
      [attr.label]="t('wealth.table.drift')"
      show-label
      show-value
      [attr.value-text]="
        t.formatPercent(drift, { maximumFractionDigits: 1, signDisplay: 'exceptZero' })
      "
    ></md-meter>
  `,
})
export class DriftMeterComponent extends ShowcaseComponent {
  @Input({ required: true }) drift!: number;

  protected get scaled(): number {
    return Math.min(10, Math.abs(this.drift) * 100);
  }

  protected get color(): MdColor {
    return driftColor(this.drift);
  }
}
