// apps/example-nuxt/app.vue
<template>
  <main style="padding:40px;font-family:system-ui,sans-serif;display:grid;gap:20px;max-width:640px">
    <h1 style="margin:0">AWC UI — Nuxt SSR (DSD)</h1>
    <p style="margin:0;color:#555">Rendered on the server with Declarative Shadow DOM, hydrated on the client.</p>
    <md-card variant="elevated">
      <div style="padding:20px;display:grid;gap:16px">
        <div style="display:flex;gap:12px;align-items:center;flex-wrap:wrap">
          <md-button variant="filled">Filled</md-button>
          <md-button variant="outlined">Outlined</md-button>
          <md-badge value="3"></md-badge>
        </div>
        <md-checkbox checked>Server-checked</md-checkbox>
      </div>
    </md-card>
  </main>
</template>

// apps/example-next/app/page.tsx
// A Next.js Server Component. It imports the SSR wrappers from
// `@awc-ui/react/server`, which server-render each component's Declarative
// Shadow DOM (via @awc-ui/core/hydrate) and hydrate on the client — so the very
// first paint is styled, no flash. Swap the import to `@awc-ui/react` for
// client-only rendering.
import { MdButton, MdCheckbox, MdBadge, MdCard } from '@awc-ui/react/server';

export default function Page() {
  return (
    <main style={{ padding: 40, fontFamily: 'system-ui, sans-serif', display: 'grid', gap: 20, maxWidth: 640 }}>
      <h1 style={{ margin: 0 }}>AWC UI — server-rendered (DSD)</h1>
      <p style={{ margin: 0, color: '#555' }}>
        These Material Design 3 web components are rendered on the server with
        Declarative Shadow DOM, then hydrated on the client.
      </p>

      <MdCard variant="elevated">
        <div style={{ padding: 20, display: 'grid', gap: 16 }}>
          <div style={{ display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}>
            <MdButton variant="filled">Filled</MdButton>
            <MdButton variant="outlined">Outlined</MdButton>
            <MdButton variant="text">Text</MdButton>
            <MdBadge value="3" />
          </div>
          <MdCheckbox checked>Server-checked</MdCheckbox>
        </div>
      </MdCard>
    </main>
  );
}
