// apps/showcase/banking/svelte/src/lib/bits/Num.svelte
<!-- A plain number: a quantity, a count, a basis-point figure. -->
<script lang="ts">
  import { t } from '$lib/showcase';

  export let value: number;
  export let digits = 0;
</script>

<span class="num">
  {$t.formatNumber(value, { maximumFractionDigits: digits, minimumFractionDigits: digits })}
</span>

// apps/showcase/wealth/vue/src/components/bits/Num.vue
<!-- A plain number: a quantity, a count, a basis-point figure. -->
<script setup lang="ts">
import { useT } from '~/composables/useShowcase';

withDefaults(defineProps<{ value: number; digits?: number }>(), { digits: 0 });

const t = useT();
</script>

<template>
  <span class="num">{{
    t.formatNumber(value, { maximumFractionDigits: digits, minimumFractionDigits: digits })
  }}</span>
</template>
