// apps/showcase/credit-risk/next/app/sectors/[sector]/page.tsx
/**
 * `/sectors/[sector]/` — one page per sector, all seven emitted at export time.
 *
 * `generateStaticParams` reads the fixture directly rather than a hard-coded
 * list, so adding a sector to the kit adds a page here without a second edit.
 * `dynamicParams = false` makes an unknown id a build-time 404 instead of a
 * silent attempt to render on demand, which a static export cannot do anyway.
 */

import { getSectors } from '@awc-ui/showcase-kit/data';
import { SectorScreen } from '@/components/screens/SectorScreen';

export const dynamicParams = false;

export function generateStaticParams() {
  return getSectors().map((sector) => ({ sector: sector.id }));
}

export default function Page({ params }: { params: { sector: string } }) {
  return <SectorScreen sectorId={params.sector} />;
}

// apps/showcase/credit-risk/nuxt/pages/sectors/[sector].vue
<!--
  `/sectors/[sector]/` — one screen per sector, seven of them in the fixture.

  There is no route list any more: the dynamic segment is matched at request
  time and the id is looked up in the kit's fixture, so adding a sector to the
  kit adds a screen here with no second edit and no rebuild.
-->
<script setup lang="ts">
import SectorScreen from '~/components/screens/SectorScreen.vue';

const route = useRoute();
const sectorId = computed(() => String(route.params.sector));
</script>

<template>
  <SectorScreen :sector-id="sectorId" />
</template>
