// apps/showcase/community/svelte/src/lib/bits/Avatar.svelte
<script lang="ts">
  import type { Person } from '@awc-ui/showcase-kit/community';
  import { t } from '$lib/showcase';
  export let person: Person;
  export let size: 'small' | 'medium' | 'large' = 'small';
</script>

<md-avatar
  src={person.avatar}
  name={person.displayName}
  initials={person.initials}
  {size}
  label={person.displayName}
  alt={$t('community.alt.arcs')}
></md-avatar>

// apps/showcase/community/vue/src/components/bits/Avatar.vue
<script setup lang="ts">
import type { Person } from '@awc-ui/showcase-kit/community';
import { useT } from '~/composables/useShowcase';

const props = withDefaults(
  defineProps<{ person: Person; size?: 'small' | 'medium' | 'large'; className?: string }>(),
  { size: 'small' },
);
const t = useT();
</script>

<template>
  <md-avatar
    :class="props.className"
    :src="props.person.avatar"
    :name="props.person.displayName"
    :initials="props.person.initials"
    :size="props.size"
    :label="props.person.displayName"
    :alt="t('community.alt.arcs')"
  />
</template>
