// apps/showcase/community/svelte/src/lib/bits/PrivacyChip.svelte
<script lang="ts">
  import { privacyIcon, privacyTone, type Group } from '@awc-ui/showcase-kit/community';
  import StateChip from './StateChip.svelte';
  export let group: Group;
</script>

<StateChip
  labelKey={group.privacyKey}
  color={privacyTone[group.privacy]}
  icon={privacyIcon[group.privacy]}
/>

// apps/showcase/community/vue/src/components/bits/PrivacyChip.vue
<!-- A group's privacy. Always shown — it changes what a non-member can see. -->
<script setup lang="ts">
import { privacyIcon, privacyTone, type Group } from '@awc-ui/showcase-kit/community';
import StateChip from './StateChip.vue';

const props = defineProps<{ group: Group }>();
</script>

<template>
  <StateChip
    :label-key="props.group.privacyKey"
    :color="privacyTone[props.group.privacy]"
    :icon="privacyIcon[props.group.privacy]"
  />
</template>
