// apps/showcase/community/svelte/src/lib/bits/RoleChip.svelte
<!-- `none` earns no chip — the join button already says they are not in it. -->
<script lang="ts">
  import { roleIcon, roleTone, type GroupRole } from '@awc-ui/showcase-kit/community';
  import StateChip from './StateChip.svelte';
  export let role: GroupRole;
</script>

{#if roleTone[role]}
  <StateChip
    labelKey={`community.role.${role}`}
    color={roleTone[role] ?? undefined}
    icon={roleIcon[role] ?? undefined}
  />
{/if}

// apps/showcase/community/vue/src/components/bits/RoleChip.vue
<!-- The viewer's role in a group. `none` earns no chip — the join button
     already says they are not in it. See `roleTone` in the kit. -->
<script setup lang="ts">
import { roleIcon, roleTone, type GroupRole } from '@awc-ui/showcase-kit/community';
import StateChip from './StateChip.vue';

const props = defineProps<{ role: GroupRole }>();
</script>

<template>
  <StateChip
    v-if="roleTone[props.role]"
    :label-key="`community.role.${props.role}`"
    :color="roleTone[props.role] ?? undefined"
    :icon="roleIcon[props.role] ?? undefined"
  />
</template>
