// apps/showcase/wealth/svelte/src/lib/screens/HouseholdSettings.svelte
<!--
  The household screen's view settings, in a side sheet.

  WHY A SIDE SHEET AND NOT A DIALOG. These four switches change what the screen
  shows while you read it — a dialog would blank the thing being configured, and
  §5.5 puts supplementary content at the side on desktop. `variant="modal"`
  rather than `standard`: a standard sheet is `role="region"` with no focus
  trap, no Escape and no focus restoration, and this one is opened from a
  toolbar button, so the reader must be able to get back to that button with the
  keyboard. The modal variant does all of that itself — §9.3 rule 4 says do not
  write your own trap, and there is none here.

  WHY SWITCHES AND NOT CHECKBOXES. Every one of them takes effect the moment it
  is flipped; there is no Apply. That is the §5.3 rule for `md-switch` — an
  instant on/off setting — and it is why the only other control in the panel is
  a reset rather than a save.

  THREE THINGS THE MANUALS SAY THAT THIS FILE DEPENDS ON:

    - `md-switch` has NO default slot. The label is not slotted content: it is
      the list row's headline, and the switch itself carries `aria-label` with
      the same words, because a bare switch has no accessible name at all.
    - `md-switch` emits `mdChange` AFTER it has already flipped itself, and it
      emits nothing when `selected` is assigned from script. So the flip cannot
      re-enter this handler, and a controlled `selected` is safe.
    - Slotted `[slot="actions"]` elements are NOT wired by the sheet. Only its
      own built-in close button calls `close()`. That built-in button is the one
      used here, and `mdClose` — which fires for the ✕, the scrim and Escape
      alike — is what puts the state back.

  WHY THE RESET IS AT THE TOP OF THE CONTENT AND NOT IN `slot="actions"`.
  M3 puts a sheet's actions in a row along its bottom edge, and that is where
  they were until the screen was looked at: `<awc-showcase-dock>` is a fixed bar
  across the bottom of the viewport with a z-index above the sheet, so the
  actions row rendered UNDERNEATH it — invisible, and unclickable. The sheet's
  modal container is `position: fixed; inset-block: 0` with no custom property
  for a bottom inset, so there is nothing to theme it out of the way with. One
  reset control at the top of a four-row panel costs nothing and is reachable.

  The switch listener is delegated to the list rather than attached per control:
  `mdChange` bubbles and is composed, and the retargeted `event.target` is the
  `md-switch` host itself, so a `data-` attribute says which one moved. Four
  element bindings for four switches is the version of this that rots.
-->
<script lang="ts" context="module">
  /**
   * What the reader has chosen to see. Pure view state — nothing here is a
   * domain value, which is exactly why it lives in the app and not in the kit.
   */
  export interface HouseholdView {
    /** Draw the benchmark beside the mandate on the growth chart. */
    benchmark: boolean;
    /** Show the 24-month sparkline on the KPI tiles. */
    trend: boolean;
    /** Keep the cash line in the allocation panel. */
    cash: boolean;
    /** Keep the asset classes that are already inside their band. */
    inBand: boolean;
  }

  /** Everything visible. "Clear" returns here, so it hides nothing. */
  export const DEFAULT_VIEW: HouseholdView = {
    benchmark: true,
    trend: true,
    cash: true,
    inBand: true,
  };

  /**
   * The rows, in order.
   *
   * `labelKey` is a dictionary key and never a string — these four are the only
   * words this file renders, and all four already exist in the shared
   * dictionary because they name things the console shows elsewhere (the
   * benchmark series, the trend column, the cash asset class, the in-band
   * allocation state).
   */
  const TOGGLES: { key: keyof HouseholdView; labelKey: string; icon: string }[] = [
    { key: 'benchmark', labelKey: 'wealth.kpi.benchmark', icon: 'timeline' },
    { key: 'trend', labelKey: 'wealth.table.trend', icon: 'show_chart' },
    { key: 'cash', labelKey: 'wealth.assetClass.cash', icon: 'savings' },
    { key: 'inBand', labelKey: 'wealth.allocationStatus.in-band', icon: 'check_circle' },
  ];
</script>

<script lang="ts">
  import { t } from '$lib/showcase';
  import ActionButton from './ActionButton.svelte';

  export let open: boolean;
  export let view: HouseholdView;
  export let onChange: (next: HouseholdView) => void;
  export let onClose: () => void;

  function onSwitchChange(event: Event) {
    const target = event.target as HTMLElement | null;
    const key = target?.dataset?.key as keyof HouseholdView | undefined;
    if (!key) return;
    onChange({ ...view, [key]: (event as CustomEvent<{ selected: boolean }>).detail.selected });
  }
</script>

<!-- A dismissal (scrim, Escape, the built-in ✕) emits mdCancel AND mdClose;
     listening to mdClose alone therefore covers every way out. -->
<md-side-sheet
  {open}
  variant="modal"
  side="end"
  headline={$t('wealth.action.filter')}
  top-divider
  on:mdClose={() => onClose()}
>
  <div class="row row--end">
    <ActionButton icon="restart_alt" onActivate={() => onChange(DEFAULT_VIEW)}>
      {$t('wealth.action.clearFilters')}
    </ActionButton>
  </div>

  <!--
    `selection-mode` is deliberately absent. Turning one on would make the list
    a `listbox` of `option`s and give every row its own selected state — a
    second, competing model beside the switch that is the real control.
    `interaction-mode="multi-action"` is the M3 shape for a settings row: the
    row is a label, the trailing control is the action.
  -->
  <md-list
    class="table-host"
    label={$t('wealth.action.filter')}
    interaction-mode="multi-action"
    on:mdChange={onSwitchChange}
  >
    {#each TOGGLES as toggle (toggle.key)}
      <md-list-item headline={$t(toggle.labelKey)} leading-icon={toggle.icon} lines="1">
        <md-switch
          slot="trailing"
          data-key={toggle.key}
          selected={view[toggle.key]}
          aria-label={$t(toggle.labelKey)}
        ></md-switch>
      </md-list-item>
    {/each}
  </md-list>
</md-side-sheet>

// apps/showcase/wealth/angular/src/app/screens/household-settings.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, EventEmitter, Input, Output } from '@angular/core';
import { ShowcaseComponent } from '../lib/screen.base';
import { ActionButtonComponent } from './household-tabs.component';

/**
 * The household screen's view settings, in a side sheet.
 *
 * WHY A SIDE SHEET AND NOT A DIALOG. These four switches change what the screen
 * shows while you read it — a dialog would blank the thing being configured,
 * and §5.5 puts supplementary content at the side on desktop. `variant="modal"`
 * rather than `standard`: a standard sheet is `role="region"` with no focus
 * trap, no Escape and no focus restoration, and this one is opened from a
 * toolbar button, so the reader must be able to get back to that button with
 * the keyboard. The modal variant does all of that itself — §9.3 rule 4 says do
 * not write your own trap, and there is none here.
 *
 * WHY SWITCHES AND NOT CHECKBOXES. Every one of them takes effect the moment it
 * is flipped; there is no Apply. That is the §5.3 rule for `md-switch` — an
 * instant on/off setting — and it is why the only other control in the panel is
 * a reset rather than a save.
 *
 * THREE THINGS THE MANUALS SAY THAT THIS FILE DEPENDS ON:
 *
 *   - `md-switch` has NO default slot. The label is not slotted content: it is
 *     the list row's headline, and the switch itself carries `aria-label` with
 *     the same words, because a bare switch has no accessible name at all.
 *   - `md-switch` emits `mdChange` AFTER it has already flipped itself, and it
 *     emits nothing when `selected` is assigned from script — or, here, when
 *     Angular rewrites the attribute. So the flip cannot re-enter the handler,
 *     and a controlled `selected` is safe.
 *   - Slotted `[slot="actions"]` elements are NOT wired by the sheet. Only its
 *     own built-in close button calls `close()`. That built-in button is the
 *     one used here, and `mdClose` — which fires for the ✕, the scrim and
 *     Escape alike — is what puts the state back. It neither bubbles nor
 *     composes, so the listener sits on the sheet element itself.
 *
 * WHY THE RESET IS AT THE TOP OF THE CONTENT AND NOT IN `slot="actions"`.
 * M3 puts a sheet's actions in a row along its bottom edge, and that is where
 * they were until the screen was looked at: `<awc-showcase-dock>` is a fixed
 * bar across the bottom of the viewport with a z-index above the sheet, so the
 * actions row rendered UNDERNEATH it — invisible, and unclickable. The sheet's
 * modal container is `position: fixed; inset-block: 0` with no custom property
 * for a bottom inset, so there is nothing to theme it out of the way with. One
 * reset control at the top of a four-row panel costs nothing and is reachable.
 *
 * The switch listener is delegated to the list rather than attached per
 * control: `mdChange` bubbles and is composed, and the retargeted
 * `event.target` is the `md-switch` host itself, so a `data-` attribute says
 * which one moved. Four template refs and four handlers for four switches is
 * the version of this that rots.
 */

/**
 * What the reader has chosen to see. Pure view state — nothing here is a domain
 * value, which is exactly why it lives in the app and not in the kit.
 */
export interface HouseholdView {
  /** Draw the benchmark beside the mandate on the growth chart. */
  benchmark: boolean;
  /** Show the 24-month sparkline on the KPI tiles. */
  trend: boolean;
  /** Keep the cash line in the allocation panel. */
  cash: boolean;
  /** Keep the asset classes that are already inside their band. */
  inBand: boolean;
}

/** Everything visible. "Clear" returns here, so it hides nothing. */
export const DEFAULT_VIEW: HouseholdView = {
  benchmark: true,
  trend: true,
  cash: true,
  inBand: true,
};

/**
 * The rows, in order.
 *
 * `labelKey` is a dictionary key and never a string — these four are the only
 * words this file renders, and all four already exist in the shared dictionary
 * because they name things the console shows elsewhere (the benchmark series,
 * the trend column, the cash asset class, the in-band allocation state).
 */
const TOGGLES: { key: keyof HouseholdView; labelKey: string; icon: string }[] = [
  { key: 'benchmark', labelKey: 'wealth.kpi.benchmark', icon: 'timeline' },
  { key: 'trend', labelKey: 'wealth.table.trend', icon: 'show_chart' },
  { key: 'cash', labelKey: 'wealth.assetClass.cash', icon: 'savings' },
  { key: 'inBand', labelKey: 'wealth.allocationStatus.in-band', icon: 'check_circle' },
];

@Component({
  selector: 'awc-household-settings',
  standalone: true,
  styles: ':host { display: contents; }',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [ActionButtonComponent],
  template: `
    <md-side-sheet
      [attr.open]="open ? '' : null"
      variant="modal"
      side="end"
      [attr.headline]="t('wealth.action.filter')"
      top-divider
      (mdClose)="closed.emit()"
    >
      <div class="row row--end">
        <md-button awcAction icon="restart_alt" (activate)="viewChange.emit(defaults)">
          {{ t('wealth.action.clearFilters') }}
        </md-button>
      </div>

      <!--
        \`selection-mode\` is deliberately absent. Turning one on would make the
        list a \`listbox\` of \`option\`s and give every row its own selected state
        — a second, competing model beside the switch that is the real control.
        \`interaction-mode="multi-action"\` is the M3 shape for a settings row:
        the row is a label, the trailing control is the action.
      -->
      <md-list
        class="table-host"
        [attr.label]="t('wealth.action.filter')"
        interaction-mode="multi-action"
        (mdChange)="onToggle($event)"
      >
        @for (toggle of toggles; track toggle.key) {
          <md-list-item
            [attr.headline]="t(toggle.labelKey)"
            [attr.leading-icon]="toggle.icon"
            lines="1"
          >
            <md-switch
              slot="trailing"
              [attr.data-key]="toggle.key"
              [attr.selected]="view[toggle.key] ? '' : null"
              [attr.aria-label]="t(toggle.labelKey)"
            ></md-switch>
          </md-list-item>
        }
      </md-list>
    </md-side-sheet>
  `,
})
export class HouseholdSettingsSheetComponent extends ShowcaseComponent {
  @Input({ required: true }) open!: boolean;
  @Input({ required: true }) view!: HouseholdView;
  @Output() readonly viewChange = new EventEmitter<HouseholdView>();
  @Output() readonly closed = new EventEmitter<void>();

  protected readonly toggles = TOGGLES;
  protected readonly defaults = DEFAULT_VIEW;

  protected onToggle(event: Event): void {
    const key = (event.target as HTMLElement | null)?.dataset?.['key'] as
      | keyof HouseholdView
      | undefined;
    if (!key) return;
    this.viewChange.emit({
      ...this.view,
      [key]: (event as CustomEvent<{ selected: boolean }>).detail.selected,
    });
  }
}
