// apps/showcase/banking/svelte/src/lib/components/Drill.svelte
<!--
  A drill link into the next screen down.

  It carries a REAL, fully-prefixed `href`, which is the whole reason this is an
  `<a>` and not a button: ⌘-click opens a tab, middle-click opens a tab, "copy
  link address" copies something that resolves, and the deep link works on a
  cold load because `scripts/fan-out-routes.mjs` writes an `index.html` at every
  route. The handler only vetoes the plain left-click.
-->
<script lang="ts">
  import { isPlainClick, navigate } from '$lib/router';
  import { withBase } from '$lib/routes';

  /** Root-relative path WITHOUT the base path — the mount is prefixed here. */
  export let href: string;

  function onClick(event: MouseEvent) {
    if (!isPlainClick(event)) return;
    event.preventDefault();
    navigate(href);
  }
</script>

<a class="drill" href={withBase(href)} on:click={onClick}><slot /></a>

// apps/showcase/banking/vue/src/components/Drill.vue
<!--
  A drill link into the next screen down.

  It carries a REAL, fully-prefixed `href`, which is the entire reason this is an
  `<a>` and not a button: ⌘-click opens a tab, middle-click opens a tab, "copy
  link address" copies something that resolves, and the deep link works on a cold
  load because the build fans `index.html` out across every route. The click
  handler only vetoes the plain left-click.

  `class` is declared before `:href` so the attribute order matches the sibling
  builds for the parity check.
-->
<script setup lang="ts">
import { isPlainActivation, useRouter } from '~/lib/router';
import { withBase } from '~/lib/routes';

const props = defineProps<{
  /** Root-relative path WITHOUT the base path — `withBase` prefixes it. */
  to: string;
}>();

const router = useRouter();

function onClick(event: MouseEvent) {
  // Anything but a plain primary click is the browser's to handle: modifier
  // clicks open tabs and windows, and a link that looks like a link and then
  // refuses to behave like one is worse than no link.
  if (!isPlainActivation(event)) return;
  event.preventDefault();
  router.push(props.to);
}
</script>

<template>
  <a class="drill" :href="withBase(to)" @click="onClick"><slot /></a>
</template>
