// apps/showcase/wealth/angular/src/app/components/sparkline.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, Input } from '@angular/core';

/**
 * The eight-point trend line inside a KPI tile or a table row.
 *
 * `data`, `labels` and `valueFormatter` have no attribute form, so they are
 * property bindings — build them with `memo()` at the call site (keyed on the
 * locale where `valueFormatter` closes over the translator) so the chart is not
 * redrawn on every change-detection pass.
 */
@Component({
  selector: 'awc-sparkline',
  standalone: true,
  styles: ':host { display: contents; }',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <md-sparkline
      [data]="data"
      [labels]="labels"
      [valueFormatter]="valueFormatter"
      variant="area"
      [attr.color]="color"
      curve="monotone"
      show-marks="extremes"
      height="34px"
    ></md-sparkline>
  `,
})
export class SparklineComponent {
  @Input({ required: true }) data!: (number | null)[];
  /** Tooltip x labels — month ends, already formatted. */
  @Input() labels?: string[];
  @Input() valueFormatter?: (value: number | null) => string;
  @Input() color = 'primary';
}

// apps/showcase/banking/vue/src/components/Sparkline.vue
<!--
  The tiny trend line inside a KPI tile or a table row.

  `data`, `labels` and `valueFormatter` are object/function props with no
  attribute form, so they go through `v-awc`. The formatter closes over the
  translator, and `v-awc` re-assigns props on every update, so a locale switch
  re-labels the tooltip without any extra wiring. Everything else (`variant`,
  `color`, `curve`, `height`, …) falls through as an attribute.
-->
<script setup lang="ts">
import { computed } from 'vue';

const props = defineProps<{
  data: (number | null)[];
  /** Tooltip x labels — month ends, already formatted. */
  labels?: string[];
  valueFormatter?: (value: number | null) => string;
}>();

const objectProps = computed(() => ({
  data: props.data,
  labels: props.labels,
  valueFormatter: props.valueFormatter,
}));
</script>

<template>
  <md-sparkline v-awc="{ props: objectProps }"></md-sparkline>
</template>
